/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "QAudioDescribe.h"

typedef struct J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe {
    jclass id;

    jmethodID constructor_QAudioDescribe;
    jfieldID field_codec;
    jfieldID field_rawFormat;
    jfieldID field_samplerate;
    jfieldID field_nchannel;
    jfieldID field_bitrate;
} J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe;
static J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe;

jobject J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__QAudioDescribe(JNIEnv *env, jint codec, jint rawFormat, jint samplerate, jint nchannel, jfloat bitrate)
{
    return (*env)->NewObject(env, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.constructor_QAudioDescribe, codec, rawFormat, samplerate, nchannel, bitrate);
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__QAudioDescribe__catchAll(JNIEnv *env, jint codec, jint rawFormat, jint samplerate, jint nchannel, jfloat bitrate)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__QAudioDescribe(env, codec, rawFormat, samplerate, nchannel, bitrate);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__QAudioDescribe__asGlobalRef__catchAll(JNIEnv *env, jint codec, jint rawFormat, jint samplerate, jint nchannel, jfloat bitrate)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__QAudioDescribe__catchAll(env, codec, rawFormat, samplerate, nchannel, bitrate);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jint J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__codec__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetIntField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_codec);
}

jint J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__codec__get__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__codec__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__codec__set(JNIEnv *env, jobject thiz, jint value)
{
    (*env)->SetIntField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_codec, value);
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__codec__set__catchAll(JNIEnv *env, jobject thiz, jint value)
{
    J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__codec__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

jint J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__rawFormat__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetIntField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_rawFormat);
}

jint J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__rawFormat__get__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__rawFormat__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__rawFormat__set(JNIEnv *env, jobject thiz, jint value)
{
    (*env)->SetIntField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_rawFormat, value);
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__rawFormat__set__catchAll(JNIEnv *env, jobject thiz, jint value)
{
    J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__rawFormat__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

jint J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__samplerate__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetIntField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_samplerate);
}

jint J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__samplerate__get__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__samplerate__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__samplerate__set(JNIEnv *env, jobject thiz, jint value)
{
    (*env)->SetIntField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_samplerate, value);
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__samplerate__set__catchAll(JNIEnv *env, jobject thiz, jint value)
{
    J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__samplerate__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

jint J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__nchannel__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetIntField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_nchannel);
}

jint J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__nchannel__get__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__nchannel__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__nchannel__set(JNIEnv *env, jobject thiz, jint value)
{
    (*env)->SetIntField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_nchannel, value);
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__nchannel__set__catchAll(JNIEnv *env, jobject thiz, jint value)
{
    J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__nchannel__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

jfloat J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__bitrate__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_bitrate);
}

jfloat J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__bitrate__get__catchAll(JNIEnv *env, jobject thiz)
{
    jfloat ret_value = J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__bitrate__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__bitrate__set(JNIEnv *env, jobject thiz, jfloat value)
{
    (*env)->SetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_bitrate, value);
}

void J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__bitrate__set__catchAll(JNIEnv *env, jobject thiz, jfloat value)
{
    J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe__bitrate__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id != NULL)
        return 0;

    sign = "com/qmedia/qmediasdk/QSource/QAudioDescribe";
    class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id;
    name     = "<init>";
    sign     = "(IIIIF)V";
    class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.constructor_QAudioDescribe = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.constructor_QAudioDescribe == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id;
    name     = "codec";
    sign     = "I";
    class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_codec = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_codec == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id;
    name     = "rawFormat";
    sign     = "I";
    class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_rawFormat = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_rawFormat == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id;
    name     = "samplerate";
    sign     = "I";
    class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_samplerate = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_samplerate == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id;
    name     = "nchannel";
    sign     = "I";
    class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_nchannel = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_nchannel == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.id;
    name     = "bitrate";
    sign     = "F";
    class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_bitrate = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QAudioDescribe.field_bitrate == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.qmedia.qmediasdk.QSource.QAudioDescribe");
    ret = 0;
fail:
    return ret;
}
