/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "QAudioTarget.h"

typedef struct J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget {
    jclass id;

    jmethodID method_startAudio;
    jmethodID method_stopAudio;
    jmethodID method_pauseAudio;
    jmethodID method_resumeAudio;
    jmethodID method_flushAudio;
    jmethodID method_initAudio;
    jmethodID method_unInitAudio;
    jmethodID method_getSampleRate;
    jmethodID method_getChannels;
    jmethodID method_getFormat;
    jmethodID method_setVolume;
    jmethodID method_getVolume;
    jmethodID method_setAudioDelay;
    jmethodID method_getAudioDelay;
    jmethodID method_setRender;
    jmethodID method_getRender;
} J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget;
static J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget;

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__startAudio(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_startAudio);
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__startAudio__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__startAudio(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__stopAudio(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_stopAudio);
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__stopAudio__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__stopAudio(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__pauseAudio(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_pauseAudio);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__pauseAudio__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__pauseAudio(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__resumeAudio(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_resumeAudio);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__resumeAudio__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__resumeAudio(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__flushAudio(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_flushAudio);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__flushAudio__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__flushAudio(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__initAudio(JNIEnv *env, jobject thiz, jobject describe)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_initAudio, describe);
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__initAudio__catchAll(JNIEnv *env, jobject thiz, jobject describe)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__initAudio(env, thiz, describe);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__unInitAudio(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_unInitAudio);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__unInitAudio__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__unInitAudio(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getSampleRate(JNIEnv *env, jobject thiz)
{
    return (*env)->CallIntMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getSampleRate);
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getSampleRate__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getSampleRate(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getChannels(JNIEnv *env, jobject thiz)
{
    return (*env)->CallIntMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getChannels);
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getChannels__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getChannels(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getFormat(JNIEnv *env, jobject thiz)
{
    return (*env)->CallIntMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getFormat);
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getFormat__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getFormat(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__setVolume(JNIEnv *env, jobject thiz, jfloat volume)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_setVolume, volume);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__setVolume__catchAll(JNIEnv *env, jobject thiz, jfloat volume)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__setVolume(env, thiz, volume);
    J4A_ExceptionCheck__catchAll(env);
}

jfloat J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getVolume(JNIEnv *env, jobject thiz)
{
    return (*env)->CallFloatMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getVolume);
}

jfloat J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getVolume__catchAll(JNIEnv *env, jobject thiz)
{
    jfloat ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getVolume(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__setAudioDelay(JNIEnv *env, jobject thiz, jint audioDelay)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_setAudioDelay, audioDelay);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__setAudioDelay__catchAll(JNIEnv *env, jobject thiz, jint audioDelay)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__setAudioDelay(env, thiz, audioDelay);
    J4A_ExceptionCheck__catchAll(env);
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getAudioDelay(JNIEnv *env, jobject thiz)
{
    return (*env)->CallIntMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getAudioDelay);
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getAudioDelay__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getAudioDelay(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__setRender(JNIEnv *env, jobject thiz, jobject audioRender)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_setRender, audioRender);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__setRender__catchAll(JNIEnv *env, jobject thiz, jobject audioRender)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__setRender(env, thiz, audioRender);
    J4A_ExceptionCheck__catchAll(env);
}

jobject J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getRender(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getRender);
}

jobject J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getRender__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getRender(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getRender__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget__getRender__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id != NULL)
        return 0;

    sign = "com/qmedia/qmediasdk/QTarget/QAudioTarget";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "startAudio";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_startAudio = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_startAudio == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "stopAudio";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_stopAudio = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_stopAudio == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "pauseAudio";
    sign     = "()V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_pauseAudio = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_pauseAudio == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "resumeAudio";
    sign     = "()V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_resumeAudio = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_resumeAudio == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "flushAudio";
    sign     = "()V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_flushAudio = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_flushAudio == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "initAudio";
    sign     = "(Lcom/qmedia/qmediasdk/QSource/QAudioDescribe;)Z";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_initAudio = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_initAudio == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "unInitAudio";
    sign     = "()V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_unInitAudio = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_unInitAudio == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "getSampleRate";
    sign     = "()I";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getSampleRate = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getSampleRate == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "getChannels";
    sign     = "()I";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getChannels = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getChannels == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "getFormat";
    sign     = "()I";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getFormat = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getFormat == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "setVolume";
    sign     = "(F)V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_setVolume = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_setVolume == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "getVolume";
    sign     = "()F";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getVolume = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getVolume == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "setAudioDelay";
    sign     = "(I)V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_setAudioDelay = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_setAudioDelay == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "getAudioDelay";
    sign     = "()I";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getAudioDelay = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getAudioDelay == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "setRender";
    sign     = "(Lcom/qmedia/qmediasdk/QTarget/QAudioRender;)V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_setRender = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_setRender == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.id;
    name     = "getRender";
    sign     = "()Lcom/qmedia/qmediasdk/QTarget/QAudioRender;";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getRender = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioTarget.method_getRender == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.qmedia.qmediasdk.QTarget.QAudioTarget");
    ret = 0;
fail:
    return ret;
}
