/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "QAudioRender.h"

typedef struct J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender {
    jclass id;

    jmethodID method_onAudioRender;
} J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender;
static J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender;

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender__onAudioRender(JNIEnv *env, jobject thiz, jobject buffer, jint needBytes, jlong wantTime)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender.method_onAudioRender, buffer, needBytes, wantTime);
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender__onAudioRender__catchAll(JNIEnv *env, jobject thiz, jobject buffer, jint needBytes, jlong wantTime)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender__onAudioRender(env, thiz, buffer, needBytes, wantTime);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender.id != NULL)
        return 0;

    sign = "com/qmedia/qmediasdk/QTarget/QAudioRender";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender.id == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender.id;
    name     = "onAudioRender";
    sign     = "(Ljava/nio/ByteBuffer;IJ)Z";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender.method_onAudioRender = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QAudioRender.method_onAudioRender == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.qmedia.qmediasdk.QTarget.QAudioRender");
    ret = 0;
fail:
    return ret;
}
