/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__com_qmedia_qmediasdk_QGraphic_QBlendFunc__H
#define J4A__com_qmedia_qmediasdk_QGraphic_QBlendFunc__H

#include "j4a/j4a_base.h"

jobject J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__QBlendFunc(JNIEnv *env, jint src, jint dst);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__QBlendFunc__catchAll(JNIEnv *env, jint src, jint dst);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__QBlendFunc__asGlobalRef__catchAll(JNIEnv *env, jint src, jint dst);
jint J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__src__get(JNIEnv *env, jobject thiz);
jint J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__src__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__src__set(JNIEnv *env, jobject thiz, jint value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__src__set__catchAll(JNIEnv *env, jobject thiz, jint value);
jint J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__dst__get(JNIEnv *env, jobject thiz);
jint J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__dst__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__dst__set(JNIEnv *env, jobject thiz, jint value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc__dst__set__catchAll(JNIEnv *env, jobject thiz, jint value);
int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QGraphic_QBlendFunc(JNIEnv *env);

#endif//J4A__com_qmedia_qmediasdk_QGraphic_QBlendFunc__H
