/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__com_qmedia_qmediasdk_QEditor_QEditorPlayer__H
#define J4A__com_qmedia_qmediasdk_QEditor_QEditorPlayer__H

#include "j4a/j4a_base.h"

void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onPrepare(JNIEnv *env, jobject thiz, jint errcode);
void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onPrepare__catchAll(JNIEnv *env, jobject thiz, jint errcode);
void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onPlayerStateChanged(JNIEnv *env, jobject thiz, jint newState, jint oldState);
void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onPlayerStateChanged__catchAll(JNIEnv *env, jobject thiz, jint newState, jint oldState);
void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onPlayerTimeProgressUpdated(JNIEnv *env, jobject thiz, jlong progress);
void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onPlayerTimeProgressUpdated__catchAll(JNIEnv *env, jobject thiz, jlong progress);
void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onSeekTo(JNIEnv *env, jobject thiz, jlong mSec);
void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onSeekTo__catchAll(JNIEnv *env, jobject thiz, jlong mSec);
void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onCompleted(JNIEnv *env, jobject thiz, jint errcode);
void J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer__onCompleted__catchAll(JNIEnv *env, jobject thiz, jint errcode);
int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QEditor_QEditorPlayer(JNIEnv *env);

#endif//J4A__com_qmedia_qmediasdk_QEditor_QEditorPlayer__H
