/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__com_qmedia_qmediasdk_QEffect_QEffectConfig__H
#define J4A__com_qmedia_qmediasdk_QEffect_QEffectConfig__H

#include "j4a/j4a_base.h"

jobject J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__QEffectConfig(JNIEnv *env, jstring name, jstring describe, jstring type);
jobject J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__QEffectConfig__catchAll(JNIEnv *env, jstring name, jstring describe, jstring type);
jobject J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__QEffectConfig__asGlobalRef__catchAll(JNIEnv *env, jstring name, jstring describe, jstring type);
jobject J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__QEffectConfig__withCString(JNIEnv *env, const char *name_cstr__, const char *describe_cstr__, const char *type_cstr__);
jobject J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__QEffectConfig__withCString__catchAll(JNIEnv *env, const char *name_cstr__, const char *describe_cstr__, const char *type_cstr__);
jobject J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__QEffectConfig__withCString__asGlobalRef__catchAll(JNIEnv *env, const char *name_cstr__, const char *describe_cstr__, const char *type_cstr__);
jstring J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__name__get(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__name__get__catchAll(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__name__get__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
const char *J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__name__get__asCBuffer(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
const char *J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__name__get__asCBuffer__catchAll(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__name__set(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__name__set__catchAll(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__name__set__withCString(JNIEnv *env, jobject thiz, const char *value_cstr__);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__name__set__withCString__catchAll(JNIEnv *env, jobject thiz, const char *value_cstr__);
jstring J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__describe__get(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__describe__get__catchAll(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__describe__get__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
const char *J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__describe__get__asCBuffer(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
const char *J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__describe__get__asCBuffer__catchAll(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__describe__set(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__describe__set__catchAll(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__describe__set__withCString(JNIEnv *env, jobject thiz, const char *value_cstr__);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__describe__set__withCString__catchAll(JNIEnv *env, jobject thiz, const char *value_cstr__);
jstring J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__type__get(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__type__get__catchAll(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__type__get__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
const char *J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__type__get__asCBuffer(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
const char *J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__type__get__asCBuffer__catchAll(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__type__set(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__type__set__catchAll(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__type__set__withCString(JNIEnv *env, jobject thiz, const char *value_cstr__);
void J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig__type__set__withCString__catchAll(JNIEnv *env, jobject thiz, const char *value_cstr__);
int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QEffect_QEffectConfig(JNIEnv *env);

#endif//J4A__com_qmedia_qmediasdk_QEffect_QEffectConfig__H
