/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__com_qmedia_qmediasdk_QEditor_QExporter__H
#define J4A__com_qmedia_qmediasdk_QEditor_QExporter__H

#include "j4a/j4a_base.h"

void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterStarted(JNIEnv *env, jobject thiz, jint code);
void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterStarted__catchAll(JNIEnv *env, jobject thiz, jint code);
void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterStoped(JNIEnv *env, jobject thiz, jint code);
void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterStoped__catchAll(JNIEnv *env, jobject thiz, jint code);
void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterProgressUpdated(JNIEnv *env, jobject thiz, jlong progress);
void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterProgressUpdated__catchAll(JNIEnv *env, jobject thiz, jlong progress);
void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterCanceled(JNIEnv *env, jobject thiz, jint code);
void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterCanceled__catchAll(JNIEnv *env, jobject thiz, jint code);
void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterCompleted(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QEditor_QExporter__onExporterCompleted__catchAll(JNIEnv *env, jobject thiz);
int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QEditor_QExporter(JNIEnv *env);

#endif//J4A__com_qmedia_qmediasdk_QEditor_QExporter__H
