/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "QMediaSource.h"

typedef struct J4AC_com_qmedia_qmediasdk_QSource_QMediaSource {
    jclass id;

    jmethodID method_setVideoTarget;
    jmethodID method_setAudioTarget;
    jmethodID method_getVideoTarget;
    jmethodID method_getAudioTarget;
    jmethodID method_getVideoDescribe;
    jmethodID method_getAudioDescribe;
    jmethodID method_load;
    jmethodID method_unload;
    jmethodID method_isInit;
    jmethodID method_start;
    jmethodID method_stop;
    jmethodID method_seekTo;
    jmethodID method_isEOF;
    jmethodID method_isStarted;
    jmethodID method_getMediaDuration;
    jmethodID method_readNextVideoFrame;
    jmethodID method_readNextAudioFrame;
} J4AC_com_qmedia_qmediasdk_QSource_QMediaSource;
static J4AC_com_qmedia_qmediasdk_QSource_QMediaSource class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource;

void J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__setVideoTarget(JNIEnv *env, jobject thiz, jobject videoTarget)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_setVideoTarget, videoTarget);
}

void J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__setVideoTarget__catchAll(JNIEnv *env, jobject thiz, jobject videoTarget)
{
    J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__setVideoTarget(env, thiz, videoTarget);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__setAudioTarget(JNIEnv *env, jobject thiz, jobject audioTarget)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_setAudioTarget, audioTarget);
}

void J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__setAudioTarget__catchAll(JNIEnv *env, jobject thiz, jobject audioTarget)
{
    J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__setAudioTarget(env, thiz, audioTarget);
    J4A_ExceptionCheck__catchAll(env);
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoTarget(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getVideoTarget);
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoTarget__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoTarget(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoTarget__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoTarget__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioTarget(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getAudioTarget);
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioTarget__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioTarget(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioTarget__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioTarget__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoDescribe(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getVideoDescribe);
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoDescribe__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoDescribe(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoDescribe__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getVideoDescribe__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioDescribe(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getAudioDescribe);
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioDescribe__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioDescribe(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioDescribe__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getAudioDescribe__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__load(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_load);
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__load__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__load(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__unload(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_unload);
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__unload__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__unload(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__isInit(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_isInit);
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__isInit__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__isInit(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__start(JNIEnv *env, jobject thiz, jlong startMSec, jlong endMSec)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_start, startMSec, endMSec);
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__start__catchAll(JNIEnv *env, jobject thiz, jlong startMSec, jlong endMSec)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__start(env, thiz, startMSec, endMSec);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__stop(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_stop);
}

void J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__stop__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__stop(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__seekTo(JNIEnv *env, jobject thiz, jlong mSec)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_seekTo, mSec);
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__seekTo__catchAll(JNIEnv *env, jobject thiz, jlong mSec)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__seekTo(env, thiz, mSec);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__isEOF(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_isEOF);
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__isEOF__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__isEOF(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__isStarted(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_isStarted);
}

jboolean J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__isStarted__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__isStarted(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jlong J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getMediaDuration(JNIEnv *env, jobject thiz)
{
    return (*env)->CallLongMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getMediaDuration);
}

jlong J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getMediaDuration__catchAll(JNIEnv *env, jobject thiz)
{
    jlong ret_value = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__getMediaDuration(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextVideoFrame(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_readNextVideoFrame);
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextVideoFrame__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextVideoFrame(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextVideoFrame__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextVideoFrame__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextAudioFrame(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_readNextAudioFrame);
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextAudioFrame__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextAudioFrame(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextAudioFrame__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QSource_QMediaSource__readNextAudioFrame__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QSource_QMediaSource(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id != NULL)
        return 0;

    sign = "com/qmedia/qmediasdk/QSource/QMediaSource";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "setVideoTarget";
    sign     = "(Lcom/qmedia/qmediasdk/QTarget/QVideoTarget;)V";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_setVideoTarget = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_setVideoTarget == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "setAudioTarget";
    sign     = "(Lcom/qmedia/qmediasdk/QTarget/QAudioTarget;)V";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_setAudioTarget = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_setAudioTarget == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "getVideoTarget";
    sign     = "()Lcom/qmedia/qmediasdk/QTarget/QVideoTarget;";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getVideoTarget = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getVideoTarget == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "getAudioTarget";
    sign     = "()Lcom/qmedia/qmediasdk/QTarget/QAudioTarget;";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getAudioTarget = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getAudioTarget == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "getVideoDescribe";
    sign     = "()Lcom/qmedia/qmediasdk/QSource/QVideoDescribe;";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getVideoDescribe = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getVideoDescribe == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "getAudioDescribe";
    sign     = "()Lcom/qmedia/qmediasdk/QSource/QAudioDescribe;";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getAudioDescribe = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getAudioDescribe == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "load";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_load = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_load == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "unload";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_unload = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_unload == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "isInit";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_isInit = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_isInit == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "start";
    sign     = "(JJ)Z";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_start = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_start == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "stop";
    sign     = "()V";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_stop = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_stop == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "seekTo";
    sign     = "(J)Z";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_seekTo = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_seekTo == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "isEOF";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_isEOF = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_isEOF == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "isStarted";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_isStarted = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_isStarted == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "getMediaDuration";
    sign     = "()J";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getMediaDuration = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_getMediaDuration == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "readNextVideoFrame";
    sign     = "()Lcom/qmedia/qmediasdk/QGraphic/QVideoFrame;";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_readNextVideoFrame = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_readNextVideoFrame == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.id;
    name     = "readNextAudioFrame";
    sign     = "()Lcom/qmedia/qmediasdk/QAudio/QAudioFrame;";
    class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_readNextAudioFrame = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QSource_QMediaSource.method_readNextAudioFrame == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.qmedia.qmediasdk.QSource.QMediaSource");
    ret = 0;
fail:
    return ret;
}
