/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__com_qmedia_qmediasdk_QGraphic_QNodeAnimator__H
#define J4A__com_qmedia_qmediasdk_QGraphic_QNodeAnimator__H

#include "j4a/j4a_base.h"

jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__QNodeAnimator(JNIEnv *env, jstring property, jobject timeRang, jobject beginPoint, jobject endPoint, jint functionType, jboolean repleat, jstring name);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__QNodeAnimator__catchAll(JNIEnv *env, jstring property, jobject timeRang, jobject beginPoint, jobject endPoint, jint functionType, jboolean repleat, jstring name);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__QNodeAnimator__asGlobalRef__catchAll(JNIEnv *env, jstring property, jobject timeRang, jobject beginPoint, jobject endPoint, jint functionType, jboolean repleat, jstring name);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__QNodeAnimator__withCString(JNIEnv *env, const char *property_cstr__, jobject timeRang, jobject beginPoint, jobject endPoint, jint functionType, jboolean repleat, const char *name_cstr__);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__QNodeAnimator__withCString__catchAll(JNIEnv *env, const char *property_cstr__, jobject timeRang, jobject beginPoint, jobject endPoint, jint functionType, jboolean repleat, const char *name_cstr__);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__QNodeAnimator__withCString__asGlobalRef__catchAll(JNIEnv *env, const char *property_cstr__, jobject timeRang, jobject beginPoint, jobject endPoint, jint functionType, jboolean repleat, const char *name_cstr__);
jstring J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__property__get(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__property__get__catchAll(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__property__get__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
const char *J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__property__get__asCBuffer(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
const char *J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__property__get__asCBuffer__catchAll(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__property__set(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__property__set__catchAll(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__property__set__withCString(JNIEnv *env, jobject thiz, const char *value_cstr__);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__property__set__withCString__catchAll(JNIEnv *env, jobject thiz, const char *value_cstr__);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__timeRang__get(JNIEnv *env, jobject thiz);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__timeRang__get__catchAll(JNIEnv *env, jobject thiz);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__timeRang__get__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__timeRang__set(JNIEnv *env, jobject thiz, jobject value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__timeRang__set__catchAll(JNIEnv *env, jobject thiz, jobject value);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__beginPoint__get(JNIEnv *env, jobject thiz);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__beginPoint__get__catchAll(JNIEnv *env, jobject thiz);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__beginPoint__get__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__beginPoint__set(JNIEnv *env, jobject thiz, jobject value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__beginPoint__set__catchAll(JNIEnv *env, jobject thiz, jobject value);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__endPoint__get(JNIEnv *env, jobject thiz);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__endPoint__get__catchAll(JNIEnv *env, jobject thiz);
jobject J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__endPoint__get__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__endPoint__set(JNIEnv *env, jobject thiz, jobject value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__endPoint__set__catchAll(JNIEnv *env, jobject thiz, jobject value);
jint J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__functionType__get(JNIEnv *env, jobject thiz);
jint J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__functionType__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__functionType__set(JNIEnv *env, jobject thiz, jint value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__functionType__set__catchAll(JNIEnv *env, jobject thiz, jint value);
jstring J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__name__get(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__name__get__catchAll(JNIEnv *env, jobject thiz);
jstring J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__name__get__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
const char *J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__name__get__asCBuffer(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
const char *J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__name__get__asCBuffer__catchAll(JNIEnv *env, jobject thiz, char *out_buf, int out_len);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__name__set(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__name__set__catchAll(JNIEnv *env, jobject thiz, jstring value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__name__set__withCString(JNIEnv *env, jobject thiz, const char *value_cstr__);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__name__set__withCString__catchAll(JNIEnv *env, jobject thiz, const char *value_cstr__);
jboolean J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__repleat__get(JNIEnv *env, jobject thiz);
jboolean J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__repleat__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__repleat__set(JNIEnv *env, jobject thiz, jboolean value);
void J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator__repleat__set__catchAll(JNIEnv *env, jobject thiz, jboolean value);
int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QGraphic_QNodeAnimator(JNIEnv *env);

#endif//J4A__com_qmedia_qmediasdk_QGraphic_QNodeAnimator__H
