/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "QSize.h"

typedef struct J4AC_com_qmedia_qmediasdk_QCommon_QSize {
    jclass id;

    jmethodID constructor_QSize;
    jmethodID method_isZero;
    jfieldID field_width;
    jfieldID field_height;
} J4AC_com_qmedia_qmediasdk_QCommon_QSize;
static J4AC_com_qmedia_qmediasdk_QCommon_QSize class_J4AC_com_qmedia_qmediasdk_QCommon_QSize;

jobject J4AC_com_qmedia_qmediasdk_QCommon_QSize__QSize(JNIEnv *env, jfloat width, jfloat height)
{
    return (*env)->NewObject(env, class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.id, class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.constructor_QSize, width, height);
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QSize__QSize__catchAll(JNIEnv *env, jfloat width, jfloat height)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QCommon_QSize__QSize(env, width, height);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QSize__QSize__asGlobalRef__catchAll(JNIEnv *env, jfloat width, jfloat height)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QCommon_QSize__QSize__catchAll(env, width, height);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jboolean J4AC_com_qmedia_qmediasdk_QCommon_QSize__isZero(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.method_isZero);
}

jboolean J4AC_com_qmedia_qmediasdk_QCommon_QSize__isZero__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QCommon_QSize__isZero(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QSize__width__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.field_width);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QSize__width__get__catchAll(JNIEnv *env, jobject thiz)
{
    jfloat ret_value = J4AC_com_qmedia_qmediasdk_QCommon_QSize__width__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QCommon_QSize__width__set(JNIEnv *env, jobject thiz, jfloat value)
{
    (*env)->SetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.field_width, value);
}

void J4AC_com_qmedia_qmediasdk_QCommon_QSize__width__set__catchAll(JNIEnv *env, jobject thiz, jfloat value)
{
    J4AC_com_qmedia_qmediasdk_QCommon_QSize__width__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QSize__height__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.field_height);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QSize__height__get__catchAll(JNIEnv *env, jobject thiz)
{
    jfloat ret_value = J4AC_com_qmedia_qmediasdk_QCommon_QSize__height__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QCommon_QSize__height__set(JNIEnv *env, jobject thiz, jfloat value)
{
    (*env)->SetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.field_height, value);
}

void J4AC_com_qmedia_qmediasdk_QCommon_QSize__height__set__catchAll(JNIEnv *env, jobject thiz, jfloat value)
{
    J4AC_com_qmedia_qmediasdk_QCommon_QSize__height__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QCommon_QSize(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.id != NULL)
        return 0;

    sign = "com/qmedia/qmediasdk/QCommon/QSize";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.id == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.id;
    name     = "<init>";
    sign     = "(FF)V";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.constructor_QSize = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.constructor_QSize == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.id;
    name     = "isZero";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.method_isZero = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.method_isZero == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.id;
    name     = "width";
    sign     = "F";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.field_width = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.field_width == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.id;
    name     = "height";
    sign     = "F";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.field_height = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QSize.field_height == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.qmedia.qmediasdk.QCommon.QSize");
    ret = 0;
fail:
    return ret;
}
