/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__com_qmedia_qmediasdk_QCommon_QVector__H
#define J4A__com_qmedia_qmediasdk_QCommon_QVector__H

#include "j4a/j4a_base.h"

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector1(JNIEnv *env, jfloat v0);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector1__catchAll(JNIEnv *env, jfloat v0);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector1__asGlobalRef__catchAll(JNIEnv *env, jfloat v0);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector2(JNIEnv *env, jfloat v0, jfloat v1);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector2__catchAll(JNIEnv *env, jfloat v0, jfloat v1);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector2__asGlobalRef__catchAll(JNIEnv *env, jfloat v0, jfloat v1);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector3(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector3__catchAll(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector3__asGlobalRef__catchAll(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector4(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2, jfloat v3);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector4__catchAll(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2, jfloat v3);
jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector4__asGlobalRef__catchAll(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2, jfloat v3);
jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__get(JNIEnv *env, jobject thiz);
jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__set(JNIEnv *env, jobject thiz, jfloat value);
void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__set__catchAll(JNIEnv *env, jobject thiz, jfloat value);
jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__get(JNIEnv *env, jobject thiz);
jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__set(JNIEnv *env, jobject thiz, jfloat value);
void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__set__catchAll(JNIEnv *env, jobject thiz, jfloat value);
jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__get(JNIEnv *env, jobject thiz);
jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__set(JNIEnv *env, jobject thiz, jfloat value);
void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__set__catchAll(JNIEnv *env, jobject thiz, jfloat value);
jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__get(JNIEnv *env, jobject thiz);
jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__set(JNIEnv *env, jobject thiz, jfloat value);
void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__set__catchAll(JNIEnv *env, jobject thiz, jfloat value);
int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QCommon_QVector(JNIEnv *env);

#endif//J4A__com_qmedia_qmediasdk_QCommon_QVector__H
