/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "QVector.h"

typedef struct J4AC_com_qmedia_qmediasdk_QCommon_QVector {
    jclass id;

    jmethodID constructor_QVector1;
    jmethodID constructor_QVector2;
    jmethodID constructor_QVector3;
    jmethodID constructor_QVector4;
    jfieldID field_v0;
    jfieldID field_v1;
    jfieldID field_v2;
    jfieldID field_v3;
} J4AC_com_qmedia_qmediasdk_QCommon_QVector;
static J4AC_com_qmedia_qmediasdk_QCommon_QVector class_J4AC_com_qmedia_qmediasdk_QCommon_QVector;

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector1(JNIEnv *env, jfloat v0)
{
    return (*env)->NewObject(env, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector1, v0);
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector1__catchAll(JNIEnv *env, jfloat v0)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector1(env, v0);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector1__asGlobalRef__catchAll(JNIEnv *env, jfloat v0)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector1__catchAll(env, v0);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector2(JNIEnv *env, jfloat v0, jfloat v1)
{
    return (*env)->NewObject(env, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector2, v0, v1);
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector2__catchAll(JNIEnv *env, jfloat v0, jfloat v1)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector2(env, v0, v1);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector2__asGlobalRef__catchAll(JNIEnv *env, jfloat v0, jfloat v1)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector2__catchAll(env, v0, v1);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector3(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2)
{
    return (*env)->NewObject(env, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector3, v0, v1, v2);
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector3__catchAll(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector3(env, v0, v1, v2);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector3__asGlobalRef__catchAll(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector3__catchAll(env, v0, v1, v2);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector4(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2, jfloat v3)
{
    return (*env)->NewObject(env, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector4, v0, v1, v2, v3);
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector4__catchAll(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2, jfloat v3)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector4(env, v0, v1, v2, v3);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector4__asGlobalRef__catchAll(JNIEnv *env, jfloat v0, jfloat v1, jfloat v2, jfloat v3)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QCommon_QVector__QVector4__catchAll(env, v0, v1, v2, v3);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v0);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__get__catchAll(JNIEnv *env, jobject thiz)
{
    jfloat ret_value = J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__set(JNIEnv *env, jobject thiz, jfloat value)
{
    (*env)->SetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v0, value);
}

void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__set__catchAll(JNIEnv *env, jobject thiz, jfloat value)
{
    J4AC_com_qmedia_qmediasdk_QCommon_QVector__v0__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v1);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__get__catchAll(JNIEnv *env, jobject thiz)
{
    jfloat ret_value = J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__set(JNIEnv *env, jobject thiz, jfloat value)
{
    (*env)->SetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v1, value);
}

void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__set__catchAll(JNIEnv *env, jobject thiz, jfloat value)
{
    J4AC_com_qmedia_qmediasdk_QCommon_QVector__v1__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v2);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__get__catchAll(JNIEnv *env, jobject thiz)
{
    jfloat ret_value = J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__set(JNIEnv *env, jobject thiz, jfloat value)
{
    (*env)->SetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v2, value);
}

void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__set__catchAll(JNIEnv *env, jobject thiz, jfloat value)
{
    J4AC_com_qmedia_qmediasdk_QCommon_QVector__v2__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v3);
}

jfloat J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__get__catchAll(JNIEnv *env, jobject thiz)
{
    jfloat ret_value = J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__set(JNIEnv *env, jobject thiz, jfloat value)
{
    (*env)->SetFloatField(env, thiz, class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v3, value);
}

void J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__set__catchAll(JNIEnv *env, jobject thiz, jfloat value)
{
    J4AC_com_qmedia_qmediasdk_QCommon_QVector__v3__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QCommon_QVector(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id != NULL)
        return 0;

    sign = "com/qmedia/qmediasdk/QCommon/QVector";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id;
    name     = "<init>";
    sign     = "(F)V";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector1 = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector1 == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id;
    name     = "<init>";
    sign     = "(FF)V";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector2 = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector2 == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id;
    name     = "<init>";
    sign     = "(FFF)V";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector3 = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector3 == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id;
    name     = "<init>";
    sign     = "(FFFF)V";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector4 = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.constructor_QVector4 == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id;
    name     = "v0";
    sign     = "F";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v0 = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v0 == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id;
    name     = "v1";
    sign     = "F";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v1 = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v1 == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id;
    name     = "v2";
    sign     = "F";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v2 = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v2 == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.id;
    name     = "v3";
    sign     = "F";
    class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v3 = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QCommon_QVector.field_v3 == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.qmedia.qmediasdk.QCommon.QVector");
    ret = 0;
fail:
    return ret;
}
