/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "QVideoTarget.h"

typedef struct J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget {
    jclass id;

    jmethodID method_startVideo;
    jmethodID method_stopVideo;
    jmethodID method_pauseVideo;
    jmethodID method_flushVideo;
    jmethodID method_initVideo;
    jmethodID method_getTargetWidth;
    jmethodID method_getTargetHeight;
    jmethodID method_getFrameRate;
    jmethodID method_getTargetContext;
    jmethodID method_setVideoRender;
    jmethodID method_getVideoRender;
} J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget;
static J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget;

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__startVideo(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_startVideo);
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__startVideo__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__startVideo(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__stopVideo(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_stopVideo);
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__stopVideo__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__stopVideo(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

void J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__pauseVideo(JNIEnv *env, jobject thiz, jboolean isPause)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_pauseVideo, isPause);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__pauseVideo__catchAll(JNIEnv *env, jobject thiz, jboolean isPause)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__pauseVideo(env, thiz, isPause);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__flushVideo(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_flushVideo);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__flushVideo__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__flushVideo(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__initVideo(JNIEnv *env, jobject thiz, jobject describe)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_initVideo, describe);
}

jboolean J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__initVideo__catchAll(JNIEnv *env, jobject thiz, jobject describe)
{
    jboolean ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__initVideo(env, thiz, describe);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetWidth(JNIEnv *env, jobject thiz)
{
    return (*env)->CallIntMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getTargetWidth);
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetWidth__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetWidth(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetHeight(JNIEnv *env, jobject thiz)
{
    return (*env)->CallIntMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getTargetHeight);
}

jint J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetHeight__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetHeight(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jfloat J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getFrameRate(JNIEnv *env, jobject thiz)
{
    return (*env)->CallFloatMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getFrameRate);
}

jfloat J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getFrameRate__catchAll(JNIEnv *env, jobject thiz)
{
    jfloat ret_value = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getFrameRate(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jobject J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetContext(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getTargetContext);
}

jobject J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetContext__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetContext(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetContext__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getTargetContext__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

void J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__setVideoRender(JNIEnv *env, jobject thiz, jobject videoRender)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_setVideoRender, videoRender);
}

void J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__setVideoRender__catchAll(JNIEnv *env, jobject thiz, jobject videoRender)
{
    J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__setVideoRender(env, thiz, videoRender);
    J4A_ExceptionCheck__catchAll(env);
}

jobject J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getVideoRender(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getVideoRender);
}

jobject J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getVideoRender__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getVideoRender(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getVideoRender__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget__getVideoRender__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

int J4A_loadClass__J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id != NULL)
        return 0;

    sign = "com/qmedia/qmediasdk/QTarget/QVideoTarget";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "startVideo";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_startVideo = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_startVideo == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "stopVideo";
    sign     = "()Z";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_stopVideo = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_stopVideo == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "pauseVideo";
    sign     = "(Z)V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_pauseVideo = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_pauseVideo == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "flushVideo";
    sign     = "()V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_flushVideo = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_flushVideo == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "initVideo";
    sign     = "(Lcom/qmedia/qmediasdk/QSource/QVideoDescribe;)Z";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_initVideo = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_initVideo == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "getTargetWidth";
    sign     = "()I";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getTargetWidth = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getTargetWidth == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "getTargetHeight";
    sign     = "()I";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getTargetHeight = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getTargetHeight == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "getFrameRate";
    sign     = "()F";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getFrameRate = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getFrameRate == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "getTargetContext";
    sign     = "()Ljava/lang/Object;";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getTargetContext = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getTargetContext == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "setVideoRender";
    sign     = "(Lcom/qmedia/qmediasdk/QTarget/QVideoRender;)V";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_setVideoRender = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_setVideoRender == NULL)
        goto fail;

    class_id = class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.id;
    name     = "getVideoRender";
    sign     = "()Lcom/qmedia/qmediasdk/QTarget/QVideoRender;";
    class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getVideoRender = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_qmedia_qmediasdk_QTarget_QVideoTarget.method_getVideoRender == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.qmedia.qmediasdk.QTarget.QVideoTarget");
    ret = 0;
fail:
    return ret;
}
