// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_node.djinni

#pragma once

#include "djinni_support.hpp"
#include "video_render_node.h"

namespace djinni_generated {

class NativeVideoRenderNode final : ::djinni::JniInterface<::QMedia::Api::VideoRenderNode, NativeVideoRenderNode> {
public:
    using CppType = std::shared_ptr<::QMedia::Api::VideoRenderNode>;
    using CppOptType = std::shared_ptr<::QMedia::Api::VideoRenderNode>;
    using JniType = jobject;

    using Boxed = NativeVideoRenderNode;

    ~NativeVideoRenderNode();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVideoRenderNode>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVideoRenderNode>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVideoRenderNode();
    friend ::djinni::JniClass<NativeVideoRenderNode>;
    friend ::djinni::JniInterface<::QMedia::Api::VideoRenderNode, NativeVideoRenderNode>;

};

}  // namespace djinni_generated
