// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "NativeMediaRange.h"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeMediaRange::NativeMediaRange() = default;

NativeMediaRange::~NativeMediaRange() = default;

auto NativeMediaRange::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeMediaRange>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.start)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.end)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeMediaRange::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeMediaRange>::get();
    return {::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mStart)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mEnd))};
}

}  // namespace djinni_generated
