// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "NativeRect4f.h"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeRect4f::NativeRect4f() = default;

NativeRect4f::~NativeRect4f() = default;

auto NativeRect4f::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeRect4f>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.left)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.top)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.right)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.bottom)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeRect4f::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeRect4f>::get();
    return {::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mLeft)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mTop)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mRight)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mBottom))};
}

}  // namespace djinni_generated
