// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include "djinni_support.hpp"
#include "vec4.h"

namespace djinni_generated {

class NativeVec4 final {
public:
    using CppType = ::QMedia::Api::Vec4;
    using JniType = jobject;

    using Boxed = NativeVec4;

    ~NativeVec4();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeVec4();
    friend ::djinni::JniClass<NativeVec4>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/qmedia/editor/generated/Vec4") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(FFFF)V") };
    const jfieldID field_mV1 { ::djinni::jniGetFieldID(clazz.get(), "mV1", "F") };
    const jfieldID field_mV2 { ::djinni::jniGetFieldID(clazz.get(), "mV2", "F") };
    const jfieldID field_mV3 { ::djinni::jniGetFieldID(clazz.get(), "mV3", "F") };
    const jfieldID field_mV4 { ::djinni::jniGetFieldID(clazz.get(), "mV4", "F") };
};

}  // namespace djinni_generated
