// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include "djinni_support.hpp"
#include "vec3f.h"

namespace djinni_generated {

class NativeVec3f final {
public:
    using CppType = ::QMedia::Api::Vec3f;
    using JniType = jobject;

    using Boxed = NativeVec3f;

    ~NativeVec3f();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeVec3f();
    friend ::djinni::JniClass<NativeVec3f>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/qmedia/editor/generated/Vec3f") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(FFF)V") };
    const jfieldID field_mV1 { ::djinni::jniGetFieldID(clazz.get(), "mV1", "F") };
    const jfieldID field_mV2 { ::djinni::jniGetFieldID(clazz.get(), "mV2", "F") };
    const jfieldID field_mV3 { ::djinni::jniGetFieldID(clazz.get(), "mV3", "F") };
};

}  // namespace djinni_generated
