// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include "djinni_support.hpp"
#include "media_range.h"

namespace djinni_generated {

class NativeMediaRange final {
public:
    using CppType = ::QMedia::Api::MediaRange;
    using JniType = jobject;

    using Boxed = NativeMediaRange;

    ~NativeMediaRange();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeMediaRange();
    friend ::djinni::JniClass<NativeMediaRange>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/qmedia/editor/generated/MediaRange") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(JJ)V") };
    const jfieldID field_mStart { ::djinni::jniGetFieldID(clazz.get(), "mStart", "J") };
    const jfieldID field_mEnd { ::djinni::jniGetFieldID(clazz.get(), "mEnd", "J") };
};

}  // namespace djinni_generated
