// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "NativeBlendfunc.h"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeBlendfunc::NativeBlendfunc() = default;

NativeBlendfunc::~NativeBlendfunc() = default;

auto NativeBlendfunc::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeBlendfunc>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.src)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.dst)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeBlendfunc::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeBlendfunc>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mSrc)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mDst))};
}

}  // namespace djinni_generated
