// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "NativeVec4f.h"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeVec4f::NativeVec4f() = default;

NativeVec4f::~NativeVec4f() = default;

auto NativeVec4f::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeVec4f>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.v1)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.v2)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.v3)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.v4)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeVec4f::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeVec4f>::get();
    return {::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mV1)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mV2)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mV3)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mV4))};
}

}  // namespace djinni_generated
