// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_segment.djinni

#include "NativeMediaSegment.h"  // my header
#include "Marshal.hpp"
#include "NativeAudioRenderNode.h"
#include "NativeMediaRange.h"
#include "NativeMediaStreamInfo.h"
#include "NativeVideoRenderNode.h"

namespace djinni_generated {

NativeMediaSegment::NativeMediaSegment() : ::djinni::JniInterface<::QMedia::Api::MediaSegment, NativeMediaSegment>("com/qmedia/editor/generated/MediaSegment$CppProxy") {}

NativeMediaSegment::~NativeMediaSegment() = default;


CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::QMedia::Api::MediaSegment>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1getVideo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        auto r = ref->getVideo();
        return ::djinni::release(::djinni_generated::NativeVideoRenderNode::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1getAudio(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        auto r = ref->getAudio();
        return ::djinni::release(::djinni_generated::NativeAudioRenderNode::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1getMediaStreamInfo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        auto r = ref->getMediaStreamInfo();
        return ::djinni::release(::djinni::List<::djinni_generated::NativeMediaStreamInfo>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1isValid(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        auto r = ref->isValid();
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1getFileName(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        auto r = ref->getFileName();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1setTimescale(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jfloat j_timeScale)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        ref->setTimescale(::djinni::F32::toCpp(jniEnv, j_timeScale));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jfloat JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1getTimescale(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        auto r = ref->getTimescale();
        return ::djinni::release(::djinni::F32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1setSourceRange(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_range)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        ref->setSourceRange(::djinni_generated::NativeMediaRange::toCpp(jniEnv, j_range));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1getSourceRange(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        auto r = ref->getSourceRange();
        return ::djinni::release(::djinni_generated::NativeMediaRange::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1setDisplayRange(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_range)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        ref->setDisplayRange(::djinni_generated::NativeMediaRange::toCpp(jniEnv, j_range));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1getDisplayRange(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        auto r = ref->getDisplayRange();
        return ::djinni::release(::djinni_generated::NativeMediaRange::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jlong JNICALL Java_com_qmedia_editor_generated_MediaSegment_00024CppProxy_native_1getMediaDuration(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::MediaSegment>(nativeRef);
        auto r = ref->getMediaDuration();
        return ::djinni::release(::djinni::I64::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
