// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#include "NativeEditorExporterCallback.h"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeEditorExporterCallback::NativeEditorExporterCallback() : ::djinni::JniInterface<::QMedia::Api::EditorExporterCallback, NativeEditorExporterCallback>() {}

NativeEditorExporterCallback::~NativeEditorExporterCallback() = default;

NativeEditorExporterCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeEditorExporterCallback::JavaProxy::~JavaProxy() = default;

void NativeEditorExporterCallback::JavaProxy::onStarted(int32_t c_code) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeEditorExporterCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onStarted,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_code)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeEditorExporterCallback::JavaProxy::onStoped(int32_t c_code) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeEditorExporterCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onStoped,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_code)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeEditorExporterCallback::JavaProxy::onProgressUpdated(int64_t c_time_ms) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeEditorExporterCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onProgressUpdated,
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_time_ms)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeEditorExporterCallback::JavaProxy::onCanceled(int32_t c_code) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeEditorExporterCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onCanceled,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_code)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeEditorExporterCallback::JavaProxy::onCompleted() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeEditorExporterCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onCompleted);
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
