// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include "blendfunc.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBlendfunc final {
public:
    using CppType = ::QMedia::Api::Blendfunc;
    using JniType = jobject;

    using Boxed = NativeBlendfunc;

    ~NativeBlendfunc();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeBlendfunc();
    friend ::djinni::JniClass<NativeBlendfunc>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/qmedia/editor/generated/Blendfunc") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(II)V") };
    const jfieldID field_mSrc { ::djinni::jniGetFieldID(clazz.get(), "mSrc", "I") };
    const jfieldID field_mDst { ::djinni::jniGetFieldID(clazz.get(), "mDst", "I") };
};

}  // namespace djinni_generated
