// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include "djinni_support.hpp"
#include "size.h"

namespace djinni_generated {

class NativeSize final {
public:
    using CppType = ::QMedia::Api::Size;
    using JniType = jobject;

    using Boxed = NativeSize;

    ~NativeSize();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSize();
    friend ::djinni::JniClass<NativeSize>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/qmedia/editor/generated/Size") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(JJ)V") };
    const jfieldID field_mWidth { ::djinni::jniGetFieldID(clazz.get(), "mWidth", "J") };
    const jfieldID field_mHeight { ::djinni::jniGetFieldID(clazz.get(), "mHeight", "J") };
};

}  // namespace djinni_generated
