// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_segment.djinni

#pragma once

#include "djinni_support.hpp"
#include "media_segment.h"

namespace djinni_generated {

class NativeMediaSegment final : ::djinni::JniInterface<::QMedia::Api::MediaSegment, NativeMediaSegment> {
public:
    using CppType = std::shared_ptr<::QMedia::Api::MediaSegment>;
    using CppOptType = std::shared_ptr<::QMedia::Api::MediaSegment>;
    using JniType = jobject;

    using Boxed = NativeMediaSegment;

    ~NativeMediaSegment();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeMediaSegment>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeMediaSegment>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeMediaSegment();
    friend ::djinni::JniClass<NativeMediaSegment>;
    friend ::djinni::JniInterface<::QMedia::Api::MediaSegment, NativeMediaSegment>;

};

}  // namespace djinni_generated
