// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_runloop.djinni

#pragma once

#include "audio_render.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAudioRender final : ::djinni::JniInterface<::QMedia::Api::AudioRender, NativeAudioRender> {
public:
    using CppType = std::shared_ptr<::QMedia::Api::AudioRender>;
    using CppOptType = std::shared_ptr<::QMedia::Api::AudioRender>;
    using JniType = jobject;

    using Boxed = NativeAudioRender;

    ~NativeAudioRender();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAudioRender>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAudioRender>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAudioRender();
    friend ::djinni::JniClass<NativeAudioRender>;
    friend ::djinni::JniInterface<::QMedia::Api::AudioRender, NativeAudioRender>;

};

}  // namespace djinni_generated
