// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#pragma once

#include "djinni_support.hpp"
#include "editor_player_internal.h"

namespace djinni_generated {

class NativeEditorPlayerInternal final : ::djinni::JniInterface<::QMedia::Api::EditorPlayerInternal, NativeEditorPlayerInternal> {
public:
    using CppType = std::shared_ptr<::QMedia::Api::EditorPlayerInternal>;
    using CppOptType = std::shared_ptr<::QMedia::Api::EditorPlayerInternal>;
    using JniType = jobject;

    using Boxed = NativeEditorPlayerInternal;

    ~NativeEditorPlayerInternal();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeEditorPlayerInternal>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeEditorPlayerInternal>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeEditorPlayerInternal();
    friend ::djinni::JniClass<NativeEditorPlayerInternal>;
    friend ::djinni::JniInterface<::QMedia::Api::EditorPlayerInternal, NativeEditorPlayerInternal>;

};

}  // namespace djinni_generated
