// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#include "NativeEditorPlayerInternal.h"  // my header
#include "Marshal.hpp"
#include "NativeEditorPlayerCallback.h"
#include "NativeMediaSessionInternal.h"

namespace djinni_generated {

NativeEditorPlayerInternal::NativeEditorPlayerInternal() : ::djinni::JniInterface<::QMedia::Api::EditorPlayerInternal, NativeEditorPlayerInternal>("com/qmedia/editor/generated/EditorPlayerInternal$CppProxy") {}

NativeEditorPlayerInternal::~NativeEditorPlayerInternal() = default;


CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorPlayerInternal_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::QMedia::Api::EditorPlayerInternal>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_EditorPlayerInternal_00024CppProxy_native_1getSession(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorPlayerInternal>(nativeRef);
        auto r = ref->getSession();
        return ::djinni::release(::djinni_generated::NativeMediaSessionInternal::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorPlayerInternal_00024CppProxy_native_1setCallback(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorPlayerInternal>(nativeRef);
        ref->setCallback(::djinni_generated::NativeEditorPlayerCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jboolean JNICALL Java_com_qmedia_editor_generated_EditorPlayerInternal_00024CppProxy_native_1isUserPaused(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorPlayerInternal>(nativeRef);
        auto r = ref->isUserPaused();
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
