// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#pragma once

#include "djinni_support.hpp"
#include "editor_player_callback.h"

namespace djinni_generated {

class NativeEditorPlayerCallback final : ::djinni::JniInterface<::QMedia::Api::EditorPlayerCallback, NativeEditorPlayerCallback> {
public:
    using CppType = std::shared_ptr<::QMedia::Api::EditorPlayerCallback>;
    using CppOptType = std::shared_ptr<::QMedia::Api::EditorPlayerCallback>;
    using JniType = jobject;

    using Boxed = NativeEditorPlayerCallback;

    ~NativeEditorPlayerCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeEditorPlayerCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeEditorPlayerCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeEditorPlayerCallback();
    friend ::djinni::JniClass<NativeEditorPlayerCallback>;
    friend ::djinni::JniInterface<::QMedia::Api::EditorPlayerCallback, NativeEditorPlayerCallback>;

};

}  // namespace djinni_generated
