// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#include "NativeEditorExporterInternal.h"  // my header
#include "Marshal.hpp"
#include "NativeEditorExporterCallback.h"
#include "NativeMediaSessionInternal.h"

namespace djinni_generated {

NativeEditorExporterInternal::NativeEditorExporterInternal() : ::djinni::JniInterface<::QMedia::Api::EditorExporterInternal, NativeEditorExporterInternal>("com/qmedia/editor/generated/EditorExporterInternal$CppProxy") {}

NativeEditorExporterInternal::~NativeEditorExporterInternal() = default;


CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorExporterInternal_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::QMedia::Api::EditorExporterInternal>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_EditorExporterInternal_00024CppProxy_native_1getSession(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorExporterInternal>(nativeRef);
        auto r = ref->getSession();
        return ::djinni::release(::djinni_generated::NativeMediaSessionInternal::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorExporterInternal_00024CppProxy_native_1setCallback(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorExporterInternal>(nativeRef);
        ref->setCallback(::djinni_generated::NativeEditorExporterCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jlong JNICALL Java_com_qmedia_editor_generated_EditorExporterInternal_00024CppProxy_native_1getPosition(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorExporterInternal>(nativeRef);
        auto r = ref->getPosition();
        return ::djinni::release(::djinni::I64::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorExporterInternal_00024CppProxy_native_1cancel(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorExporterInternal>(nativeRef);
        ref->cancel();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
