// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include "djinni_support.hpp"
#include "video_description.h"

namespace djinni_generated {

class NativeVideoDescription final {
public:
    using CppType = ::QMedia::Api::VideoDescription;
    using JniType = jobject;

    using Boxed = NativeVideoDescription;

    ~NativeVideoDescription();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeVideoDescription();
    friend ::djinni::JniClass<NativeVideoDescription>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/qmedia/editor/generated/VideoDescription") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(IISIZ)V") };
    const jfieldID field_mWidth { ::djinni::jniGetFieldID(clazz.get(), "mWidth", "I") };
    const jfieldID field_mHeight { ::djinni::jniGetFieldID(clazz.get(), "mHeight", "I") };
    const jfieldID field_mPixelFormat { ::djinni::jniGetFieldID(clazz.get(), "mPixelFormat", "S") };
    const jfieldID field_mRotation { ::djinni::jniGetFieldID(clazz.get(), "mRotation", "I") };
    const jfieldID field_mIsTexture { ::djinni::jniGetFieldID(clazz.get(), "mIsTexture", "Z") };
};

}  // namespace djinni_generated
