// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_engine.djinni

#include "NativeMediaEngine.h"  // my header
#include "Marshal.hpp"
#include "NativeAudioDescription.h"
#include "NativeEditorExporterInternal.h"
#include "NativeEditorPlayerInternal.h"

namespace djinni_generated {

NativeMediaEngine::NativeMediaEngine() : ::djinni::JniInterface<::QMedia::Api::MediaEngine, NativeMediaEngine>("com/qmedia/editor/generated/MediaEngine$CppProxy") {}

NativeMediaEngine::~NativeMediaEngine() = default;


CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_MediaEngine_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::QMedia::Api::MediaEngine>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_qmedia_editor_generated_MediaEngine_00024CppProxy_version(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::QMedia::Api::MediaEngine::version();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_MediaEngine_00024CppProxy_configAudioOut(JNIEnv* jniEnv, jobject /*this*/, jobject j_desc)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        ::QMedia::Api::MediaEngine::config_audio_out(::djinni_generated::NativeAudioDescription::toCpp(jniEnv, j_desc));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_MediaEngine_00024CppProxy_audioOut(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::QMedia::Api::MediaEngine::audio_out();
        return ::djinni::release(::djinni_generated::NativeAudioDescription::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_MediaEngine_00024CppProxy_createEditorPlayerInternal(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::QMedia::Api::MediaEngine::create_editor_player_internal();
        return ::djinni::release(::djinni_generated::NativeEditorPlayerInternal::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_qmedia_editor_generated_MediaEngine_00024CppProxy_createEditorExporterInternal(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::QMedia::Api::MediaEngine::create_editor_exporter_internal();
        return ::djinni::release(::djinni_generated::NativeEditorExporterInternal::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
