// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#include "NativeEditorPlayerCallback.h"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeEditorPlayerCallback::NativeEditorPlayerCallback() : ::djinni::JniInterface<::QMedia::Api::EditorPlayerCallback, NativeEditorPlayerCallback>("com/qmedia/editor/generated/EditorPlayerCallback$CppProxy") {}

NativeEditorPlayerCallback::~NativeEditorPlayerCallback() = default;


CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorPlayerCallback_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::QMedia::Api::EditorPlayerCallback>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorPlayerCallback_00024CppProxy_native_1onStarted(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_code)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorPlayerCallback>(nativeRef);
        ref->onStarted(::djinni::I32::toCpp(jniEnv, j_code));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorPlayerCallback_00024CppProxy_native_1onStoped(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_code)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorPlayerCallback>(nativeRef);
        ref->onStoped(::djinni::I32::toCpp(jniEnv, j_code));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorPlayerCallback_00024CppProxy_native_1onSeekTo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jlong j_timeMs)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorPlayerCallback>(nativeRef);
        ref->onSeekTo(::djinni::I64::toCpp(jniEnv, j_timeMs));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorPlayerCallback_00024CppProxy_native_1onProgressUpdated(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jlong j_timeMs)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorPlayerCallback>(nativeRef);
        ref->onProgressUpdated(::djinni::I64::toCpp(jniEnv, j_timeMs));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorPlayerCallback_00024CppProxy_native_1onPlayerStateChanged(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_newState, jint j_oldState)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorPlayerCallback>(nativeRef);
        ref->onPlayerStateChanged(::djinni::I32::toCpp(jniEnv, j_newState),
                                  ::djinni::I32::toCpp(jniEnv, j_oldState));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_qmedia_editor_generated_EditorPlayerCallback_00024CppProxy_native_1onCompleted(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::QMedia::Api::EditorPlayerCallback>(nativeRef);
        ref->onCompleted();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
