// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#pragma once

#include "djinni_support.hpp"
#include "media_session_internal.h"

namespace djinni_generated {

class NativeMediaSessionInternal final : ::djinni::JniInterface<::QMedia::Api::MediaSessionInternal, NativeMediaSessionInternal> {
public:
    using CppType = std::shared_ptr<::QMedia::Api::MediaSessionInternal>;
    using CppOptType = std::shared_ptr<::QMedia::Api::MediaSessionInternal>;
    using JniType = jobject;

    using Boxed = NativeMediaSessionInternal;

    ~NativeMediaSessionInternal();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeMediaSessionInternal>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeMediaSessionInternal>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeMediaSessionInternal();
    friend ::djinni::JniClass<NativeMediaSessionInternal>;
    friend ::djinni::JniInterface<::QMedia::Api::MediaSessionInternal, NativeMediaSessionInternal>;

};

}  // namespace djinni_generated
