// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_engine.djinni

#pragma once

#include "djinni_support.hpp"
#include "media_engine.h"

namespace djinni_generated {

class NativeMediaEngine final : ::djinni::JniInterface<::QMedia::Api::MediaEngine, NativeMediaEngine> {
public:
    using CppType = std::shared_ptr<::QMedia::Api::MediaEngine>;
    using CppOptType = std::shared_ptr<::QMedia::Api::MediaEngine>;
    using JniType = jobject;

    using Boxed = NativeMediaEngine;

    ~NativeMediaEngine();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeMediaEngine>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeMediaEngine>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeMediaEngine();
    friend ::djinni::JniClass<NativeMediaEngine>;
    friend ::djinni::JniInterface<::QMedia::Api::MediaEngine, NativeMediaEngine>;

};

}  // namespace djinni_generated
