// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_node.djinni

#include "NativeAnimator.h"  // my header
#include "Marshal.hpp"
#include "NativeMediaRange.h"
#include "NativeVec4f.h"

namespace djinni_generated {

NativeAnimator::NativeAnimator() = default;

NativeAnimator::~NativeAnimator() = default;

auto NativeAnimator::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeAnimator>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.property)),
                                                           ::djinni::get(::djinni_generated::NativeMediaRange::fromCpp(jniEnv, c.timerang)),
                                                           ::djinni::get(::djinni_generated::NativeVec4f::fromCpp(jniEnv, c.startpoint)),
                                                           ::djinni::get(::djinni_generated::NativeVec4f::fromCpp(jniEnv, c.endpoint)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.easefunction)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.repleat)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeAnimator::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 8);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeAnimator>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mName)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mProperty)),
            ::djinni_generated::NativeMediaRange::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mTimerang)),
            ::djinni_generated::NativeVec4f::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mStartpoint)),
            ::djinni_generated::NativeVec4f::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mEndpoint)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mEasefunction)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mRepleat))};
}

}  // namespace djinni_generated
