// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from animator.djinni

#import "QEaseFunction.h"
#import "QMediaRange.h"
#import "QVec4f.h"
#import <Foundation/Foundation.h>

@interface QAnimator : NSObject
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                            property:(nonnull NSString *)property
                            timerang:(nonnull QMediaRange *)timerang
                          startpoint:(nonnull QVec4f *)startpoint
                            endpoint:(nonnull QVec4f *)endpoint
                            easefunc:(QEaseFunction)easefunc
                             repleat:(BOOL)repleat;
+ (nonnull instancetype)animatorWithName:(nonnull NSString *)name
                                property:(nonnull NSString *)property
                                timerang:(nonnull QMediaRange *)timerang
                              startpoint:(nonnull QVec4f *)startpoint
                                endpoint:(nonnull QVec4f *)endpoint
                                easefunc:(QEaseFunction)easefunc
                                 repleat:(BOOL)repleat;

@property (nonatomic , nonnull) NSString * name;

@property (nonatomic , nonnull) NSString * property;

@property (nonatomic , nonnull) QMediaRange * timerang;

@property (nonatomic , nonnull) QVec4f * startpoint;

@property (nonatomic , nonnull) QVec4f * endpoint;

@property (nonatomic ) QEaseFunction easefunc;

@property (nonatomic ) BOOL repleat;

@end

/** property */
extern NSString * __nonnull const QAnimatorPositionxyz;
extern NSString * __nonnull const QAnimatorRotation;
extern NSString * __nonnull const QAnimatorRotationxyz;
extern NSString * __nonnull const QAnimatorScalex;
extern NSString * __nonnull const QAnimatorScaley;
extern NSString * __nonnull const QAnimatorScalez;
extern NSString * __nonnull const QAnimatorScalexy;
extern NSString * __nonnull const QAnimatorScalexyz;
extern NSString * __nonnull const QAnimatorContentsizew;
extern NSString * __nonnull const QAnimatorContentsizeh;
extern NSString * __nonnull const QAnimatorContentsize;
extern NSString * __nonnull const QAnimatorAlpha;
extern NSString * __nonnull const QAnimatorMixcolor;
extern NSString * __nonnull const QAnimatorCrop;
