// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from animator.djinni

#import "QAnimator.h"


NSString * __nonnull const QAnimatorPositionxyz = @"positionxyz";

NSString * __nonnull const QAnimatorRotation = @"rotation";

NSString * __nonnull const QAnimatorRotationxyz = @"rotationxyz";

NSString * __nonnull const QAnimatorScalex = @"scalex";

NSString * __nonnull const QAnimatorScaley = @"scaley";

NSString * __nonnull const QAnimatorScalez = @"scalez";

NSString * __nonnull const QAnimatorScalexy = @"scalexy";

NSString * __nonnull const QAnimatorScalexyz = @"scalexyz";

NSString * __nonnull const QAnimatorContentsizew = @"contentsizew";

NSString * __nonnull const QAnimatorContentsizeh = @"contentsizeh";

NSString * __nonnull const QAnimatorContentsize = @"contentsize";

NSString * __nonnull const QAnimatorAlpha = @"alpha";

NSString * __nonnull const QAnimatorMixcolor = @"mixcolor";

NSString * __nonnull const QAnimatorCrop = @"crop";

@implementation QAnimator

- (nonnull instancetype)initWithName:(nonnull NSString *)name
                            property:(nonnull NSString *)property
                            timerang:(nonnull QMediaRange *)timerang
                          startpoint:(nonnull QVec4f *)startpoint
                            endpoint:(nonnull QVec4f *)endpoint
                            easefunc:(QEaseFunction)easefunc
                             repleat:(BOOL)repleat
{
    if (self = [super init]) {
        _name = [name copy];
        _property = [property copy];
        _timerang = timerang;
        _startpoint = startpoint;
        _endpoint = endpoint;
        _easefunc = easefunc;
        _repleat = repleat;
    }
    return self;
}

+ (nonnull instancetype)animatorWithName:(nonnull NSString *)name
                                property:(nonnull NSString *)property
                                timerang:(nonnull QMediaRange *)timerang
                              startpoint:(nonnull QVec4f *)startpoint
                                endpoint:(nonnull QVec4f *)endpoint
                                easefunc:(QEaseFunction)easefunc
                                 repleat:(BOOL)repleat
{
    return [(QAnimator*)[self alloc] initWithName:name
                                         property:property
                                         timerang:timerang
                                       startpoint:startpoint
                                         endpoint:endpoint
                                         easefunc:easefunc
                                          repleat:repleat];
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p name:%@ property:%@ timerang:%@ startpoint:%@ endpoint:%@ easefunc:%@ repleat:%@>", self.class, (void *)self, self.name, self.property, self.timerang, self.startpoint, self.endpoint, @(self.easefunc), @(self.repleat)];
}

@end
