// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_node.djinni

#import <Foundation/Foundation.h>


@interface QAudioRenderNode : NSObject

- (void)setTempo:(float)tempo;

- (void)setRate:(float)rate;

- (void)setPitch:(float)pitch;

- (void)setVolume:(float)volume;

@end
