// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_config.djinni

#import "QAudioEncodeOption+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto AudioEncodeOption::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.codectype),
            ::djinni::I32::toCpp(obj.nchannel),
            ::djinni::I32::toCpp(obj.samplerate),
            ::djinni::I32::toCpp(obj.bitrate),
            ::djinni::I32::toCpp(obj.sampleformat)};
}

auto AudioEncodeOption::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[QAudioEncodeOption alloc] initWithCodectype:(::djinni::I32::fromCpp(cpp.codectype))
                                                nchannel:(::djinni::I32::fromCpp(cpp.nchannel))
                                              samplerate:(::djinni::I32::fromCpp(cpp.samplerate))
                                                 bitrate:(::djinni::I32::fromCpp(cpp.bitrate))
                                            sampleformat:(::djinni::I32::fromCpp(cpp.sampleformat))];
}

}  // namespace djinni_generated
