// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_runloop.djinni

#import <Foundation/Foundation.h>


@interface QAudioRender : NSObject

/** SetPlayer(player: audio_player); */
- (int32_t)OnPlayBuffer:(nonnull id)buffer
               sizeNeed:(int32_t)sizeNeed
               wantTime:(int64_t)wantTime;

@end
