// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_node.djinni

#include "audio_render_node.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QAudioRenderNode;

namespace djinni_generated {

class AudioRenderNode
{
public:
    using CppType = std::shared_ptr<::QMedia::Api::AudioRenderNode>;
    using CppOptType = std::shared_ptr<::QMedia::Api::AudioRenderNode>;
    using ObjcType = QAudioRenderNode*;

    using Boxed = AudioRenderNode;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

