// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_config.djinni

#import "QAudioEncodeOption.h"
#include "audio_encode_option.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QAudioEncodeOption;

namespace djinni_generated {

struct AudioEncodeOption
{
    using CppType = ::QMedia::Api::AudioEncodeOption;
    using ObjcType = QAudioEncodeOption*;

    using Boxed = AudioEncodeOption;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
