// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QAudioDescription.h"
#include "audio_description.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QAudioDescription;

namespace djinni_generated {

struct AudioDescription
{
    using CppType = ::QMedia::Api::AudioDescription;
    using ObjcType = QAudioDescription*;

    using Boxed = AudioDescription;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
