// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import <Foundation/Foundation.h>
#import <Foundation/NSDictionary.h>

@interface QBlendfunc : NSObject
- (nonnull instancetype)initWithSrc:(int32_t)src
                                dst:(int32_t)dst;
+ (nonnull instancetype)blendfuncWithSrc:(int32_t)src
                                     dst:(int32_t)dst;
- (nonnull instancetype)initWithJson:(nonnull NSDictionary*)json;
- (nonnull NSDictionary*)toJson;

@property (nonatomic ) int32_t src;

@property (nonatomic ) int32_t dst;

@end

extern int32_t const QBlendfuncZERO;
extern int32_t const QBlendfuncONE;
extern int32_t const QBlendfuncSRCCOLOR;
extern int32_t const QBlendfuncONEMINUSSRCCOLOR;
extern int32_t const QBlendfuncSRCALPHA;
extern int32_t const QBlendfuncONEMINUSSRCALPHA;
extern int32_t const QBlendfuncDSTALPHA;
extern int32_t const QBlendfuncONEMINUSDSTALPHA;
extern int32_t const QBlendfuncDSTCOLOR;
extern int32_t const QBlendfuncONEMINUSDSTCOLOR;
extern int32_t const QBlendfuncSRCALPHASATURATE;
