// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QBlendfunc.h"
#include "blendfunc.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QBlendfunc;

namespace djinni_generated {

struct Blendfunc
{
    using CppType = ::QMedia::Api::Blendfunc;
    using ObjcType = QBlendfunc*;

    using Boxed = Blendfunc;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
