// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QBlendfunc.h"


int32_t const QBlendfuncZERO = 0;

int32_t const QBlendfuncONE = 1;

int32_t const QBlendfuncSRCCOLOR = 768;

int32_t const QBlendfuncONEMINUSSRCCOLOR = 769;

int32_t const QBlendfuncSRCALPHA = 770;

int32_t const QBlendfuncONEMINUSSRCALPHA = 771;

int32_t const QBlendfuncDSTALPHA = 772;

int32_t const QBlendfuncONEMINUSDSTALPHA = 773;

int32_t const QBlendfuncDSTCOLOR = 774;

int32_t const QBlendfuncONEMINUSDSTCOLOR = 775;

int32_t const QBlendfuncSRCALPHASATURATE = 776;

@implementation QBlendfunc

- (nonnull instancetype)initWithSrc:(int32_t)src
                                dst:(int32_t)dst
{
    if (self = [super init]) {
        _src = src;
        _dst = dst;
    }
    return self;
}

+ (nonnull instancetype)blendfuncWithSrc:(int32_t)src
                                     dst:(int32_t)dst
{
    return [(QBlendfunc*)[self alloc] initWithSrc:src
                                              dst:dst];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[QBlendfunc class]]) {
        return NO;
    }
    QBlendfunc *typedOther = (QBlendfunc *)other;
    return self.src == typedOther.src &&
            self.dst == typedOther.dst;
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            (NSUInteger)self.src ^
            (NSUInteger)self.dst;
}

// consturct with json
- (nonnull instancetype)initWithJson:(nonnull NSDictionary*)json {
    if (self = [super init]) {
        NSNumber* src = [json valueForKey:@"src"];
        if (src != nil) {
            _src = [src intValue];
        }
        NSNumber* dst = [json valueForKey:@"dst"];
        if (dst != nil) {
            _dst = [dst intValue];
        }
    }
    return self;
}
// serialize to json
- (nonnull NSDictionary*) toJson {
    NSDictionary* root = [NSMutableDictionary new];
    [root setValue:@(self.src) forKey:@"src"];
    [root setValue:@(self.dst) forKey:@"dst"];
    return root;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p src:%@ dst:%@>", self.class, (void *)self, @(self.src), @(self.dst)];
}

@end
