// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import "QEditorPlayerInternal.h"


int32_t const QEditorPlayerInternalEState = -3;

int32_t const QEditorPlayerInternalESystem = -2;

int32_t const QEditorPlayerInternalUnknow = -1;

int32_t const QEditorPlayerInternalOk = 0;
