// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#include "editor_exporter_callback.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol QEditorExporterCallback;

namespace djinni_generated {

class EditorExporterCallback
{
public:
    using CppType = std::shared_ptr<::QMedia::Api::EditorExporterCallback>;
    using CppOptType = std::shared_ptr<::QMedia::Api::EditorExporterCallback>;
    using ObjcType = id<QEditorExporterCallback>;

    using Boxed = EditorExporterCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

