// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import <Foundation/Foundation.h>


@protocol QEditorExporterCallback

- (void)onStarted:(int32_t)code;

- (void)onStoped:(int32_t)code;

- (void)onProgressUpdated:(int64_t)timeMs;

- (void)onCanceled:(int32_t)code;

- (void)onCompleted;

@end
