// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import "QAudioEncodeOption.h"
#import "QVideoEncodeOption.h"
#import <Foundation/Foundation.h>
@class QMediaSessionInternal;
@protocol QEditorExporterCallback;

/** error code */
extern int32_t const QEditorExporterInternalEState;
extern int32_t const QEditorExporterInternalESystem;
extern int32_t const QEditorExporterInternalUnknow;
extern int32_t const QEditorExporterInternalOk;

@interface QEditorExporterInternal : NSObject

- (nullable QMediaSessionInternal *)getSession;

- (void)setCallback:(nullable id<QEditorExporterCallback>)callback;

- (void)setAudioOption:(nonnull QAudioEncodeOption *)option;

- (void)setVideoOption:(nonnull QVideoEncodeOption *)option;

- (int64_t)getPosition;

- (void)start;

- (void)cancel;

@end
