// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#include "editor_player_internal.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QEditorPlayerInternal;

namespace djinni_generated {

class EditorPlayerInternal
{
public:
    using CppType = std::shared_ptr<::QMedia::Api::EditorPlayerInternal>;
    using CppOptType = std::shared_ptr<::QMedia::Api::EditorPlayerInternal>;
    using ObjcType = QEditorPlayerInternal*;

    using Boxed = EditorPlayerInternal;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

