// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import "QEditorExporterInternal.h"


int32_t const QEditorExporterInternalEState = -3;

int32_t const QEditorExporterInternalESystem = -2;

int32_t const QEditorExporterInternalUnknow = -1;

int32_t const QEditorExporterInternalOk = 0;
