// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import <Foundation/Foundation.h>
@class QEditorExporterCallback;
@class QMediaSessionInternal;

/** error code */
extern int32_t const QEditorExporterInternalEState;
extern int32_t const QEditorExporterInternalESystem;
extern int32_t const QEditorExporterInternalUnknow;
extern int32_t const QEditorExporterInternalOk;

@interface QEditorExporterInternal : NSObject

- (nullable QMediaSessionInternal *)getSession;

- (void)setCallback:(nullable QEditorExporterCallback *)callback;

- (void)cancel;

@end
