// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import <Foundation/Foundation.h>
@class QEditorPlayerCallback;
@class QMediaSessionInternal;

/** error code */
extern int32_t const QEditorPlayerInternalEState;
extern int32_t const QEditorPlayerInternalESystem;
extern int32_t const QEditorPlayerInternalUnknow;
extern int32_t const QEditorPlayerInternalOk;

@interface QEditorPlayerInternal : NSObject

- (nullable QMediaSessionInternal *)getSession;

- (void)setCallback:(nullable QEditorPlayerCallback *)callback;

- (BOOL)isUserPaused;

@end
