// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import <Foundation/Foundation.h>


@interface QEditorPlayerCallback : NSObject

- (void)onStarted:(int32_t)code;

- (void)onStoped:(int32_t)code;

- (void)onSeekTo:(int64_t)timeMs;

- (void)onProgressUpdated:(int64_t)timeMs;

- (void)onPlayerStateChanged:(int32_t)newState
                    oldState:(int32_t)oldState;

- (void)onCompleted;

@end
