// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import "QEditorExporterInternal+Private.h"
#import "QEditorExporterInternal.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "QEditorExporterCallback+Private.h"
#import "QMediaSessionInternal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface QEditorExporterInternal ()

- (id)initWithCpp:(const std::shared_ptr<::QMedia::Api::EditorExporterInternal>&)cppRef;

@end

@implementation QEditorExporterInternal {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::QMedia::Api::EditorExporterInternal>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::QMedia::Api::EditorExporterInternal>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nullable QMediaSessionInternal *)getSession {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getSession();
        return ::djinni_generated::MediaSessionInternal::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setCallback:(nullable QEditorExporterCallback *)callback {
    try {
        _cppRefHandle.get()->setCallback(::djinni_generated::EditorExporterCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)cancel {
    try {
        _cppRefHandle.get()->cancel();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}


namespace djinni_generated {

auto EditorExporterInternal::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto EditorExporterInternal::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<QEditorExporterInternal>(cpp);
}

}  // namespace djinni_generated

@end
