// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import <Foundation/Foundation.h>
@class QMediaSessionInternal;
@protocol QEditorPlayerCallback;

/** error code */
extern int32_t const QEditorPlayerInternalEState;
extern int32_t const QEditorPlayerInternalESystem;
extern int32_t const QEditorPlayerInternalUnknow;
extern int32_t const QEditorPlayerInternalOk;

@interface QEditorPlayerInternal : NSObject

- (nullable QMediaSessionInternal *)getSession;

- (void)setCallback:(nullable id<QEditorPlayerCallback>)callback;

- (int64_t)getPosition;

- (void)play;

- (void)pause;

- (void)seek:(int64_t)timeMs
        flag:(int32_t)flag;

- (BOOL)isUserPaused;

- (int32_t)getState;

@end
