// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QMediaRange+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto MediaRange::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.start),
            ::djinni::I64::toCpp(obj.end)};
}

auto MediaRange::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[QMediaRange alloc] initWithStart:(::djinni::I64::fromCpp(cpp.start))
                                          end:(::djinni::I64::fromCpp(cpp.end))];
}

}  // namespace djinni_generated
