// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_segment.djinni

#import "QMediaRange.h"
#import "QMediaStreamInfo.h"
#import <Foundation/Foundation.h>
@class QAudioRenderNode;
@class QVideoRenderNode;

extern int32_t const QMediaSegmentFlagVideo;
extern int32_t const QMediaSegmentFlagAudio;
extern int32_t const QMediaSegmentFlagSubtitle;
extern int32_t const QMediaSegmentFlagAll;

@interface QMediaSegment : NSObject

- (nullable QVideoRenderNode *)getVideo;

- (nullable QAudioRenderNode *)getAudio;

- (nonnull NSArray<QMediaStreamInfo *> *)getMediaStreamInfo;

- (BOOL)isValid;

- (nonnull NSString *)getFileName;

- (void)setTimescale:(float)timeScale;

- (float)getTimescale;

- (void)setSourceRange:(nonnull QMediaRange *)range;

- (nonnull QMediaRange *)getSourceRange;

- (void)setDisplayRange:(nonnull QMediaRange *)range;

- (nonnull QMediaRange *)getDisplayRange;

- (int64_t)getMediaDuration;

@end
