// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_segment.djinni

#import "QMediaSegment.h"


int32_t const QMediaSegmentFlagVideo = 1;

int32_t const QMediaSegmentFlagAudio = 2;

int32_t const QMediaSegmentFlagSubtitle = 4;

int32_t const QMediaSegmentFlagAll = 7;
