// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QMediaStreamInfo+Private.h"
#import "DJIMarshal+Private.h"
#import "QAudioDescription+Private.h"
#import "QVideoDescription+Private.h"
#include <cassert>

namespace djinni_generated {

auto MediaStreamInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.mediaType),
            ::djinni::I32::toCpp(obj.codecType),
            ::djinni::I64::toCpp(obj.duration),
            ::djinni::I64::toCpp(obj.bitrate),
            ::djinni::I32::toCpp(obj.streamId),
            ::djinni::List<::djinni::I64>::toCpp(obj.gops),
            ::djinni::I32::toCpp(obj.timebaseNum),
            ::djinni::I32::toCpp(obj.timebaseDen),
            ::djinni_generated::AudioDescription::toCpp(obj.aDesc),
            ::djinni_generated::VideoDescription::toCpp(obj.vDesc)};
}

auto MediaStreamInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[QMediaStreamInfo alloc] initWithMediaType:(::djinni::I32::fromCpp(cpp.media_type))
                                             codecType:(::djinni::I32::fromCpp(cpp.codec_type))
                                              duration:(::djinni::I64::fromCpp(cpp.duration))
                                               bitrate:(::djinni::I64::fromCpp(cpp.bitrate))
                                              streamId:(::djinni::I32::fromCpp(cpp.stream_id))
                                                  gops:(::djinni::List<::djinni::I64>::fromCpp(cpp.gops))
                                           timebaseNum:(::djinni::I32::fromCpp(cpp.timebase_num))
                                           timebaseDen:(::djinni::I32::fromCpp(cpp.timebase_den))
                                                 aDesc:(::djinni_generated::AudioDescription::fromCpp(cpp.a_desc))
                                                 vDesc:(::djinni_generated::VideoDescription::fromCpp(cpp.v_desc))];
}

}  // namespace djinni_generated
