// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#import "QSize.h"
#import "QTimeRange.h"
#import "QVec4.h"
#import <Foundation/Foundation.h>
@class QMediaSegment;


@interface QMediaSessionInternal : NSObject

- (nullable QMediaSegment *)cresteMediaSegment:(nonnull NSString *)filename
                                          mode:(int32_t)mode;

- (BOOL)addMediaSegment:(nullable QMediaSegment *)segment;

- (BOOL)removeMediaSegment:(nullable QMediaSegment *)segment;

- (nonnull QTimeRange *)getTotalTimeRange;

- (void)setDisplayLayerSize:(nonnull QSize *)size;

- (nonnull QSize *)getDisplayLayerSize;

- (void)setBkColor:(nonnull QVec4 *)color;

- (nonnull QVec4 *)getBkColor;

/** control */
- (void)start;

- (void)stop;

- (void)pause;

- (void)resume;

- (void)seek:(int64_t)timeMs
        flag:(int32_t)flag;

- (int64_t)getPosition;

@end
