// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_segment.djinni

#import "QAudioDescription.h"
#import "QVideoDescription.h"
#import <Foundation/Foundation.h>

@interface QMediaStreamInfo : NSObject
- (nonnull instancetype)initWithMediaType:(int32_t)mediaType
                                 duration:(int64_t)duration
                                     gops:(nonnull NSArray<NSNumber *> *)gops
                                audioDesc:(nullable QAudioDescription *)audioDesc
                                videoDesc:(nullable QVideoDescription *)videoDesc;
+ (nonnull instancetype)mediaStreamInfoWithMediaType:(int32_t)mediaType
                                            duration:(int64_t)duration
                                                gops:(nonnull NSArray<NSNumber *> *)gops
                                           audioDesc:(nullable QAudioDescription *)audioDesc
                                           videoDesc:(nullable QVideoDescription *)videoDesc;

@property (nonatomic, readonly) int32_t mediaType;

@property (nonatomic, readonly) int64_t duration;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * gops;

@property (nonatomic, readonly, nullable) QAudioDescription * audioDesc;

@property (nonatomic, readonly, nullable) QVideoDescription * videoDesc;

@end

extern int32_t const QMediaStreamInfoMediaUnknow;
extern int32_t const QMediaStreamInfoMediaVideo;
extern int32_t const QMediaStreamInfoMediaAudio;
