// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_segment.djinni

#import "QMediaStreamInfo.h"
#include "media_stream_info.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QMediaStreamInfo;

namespace djinni_generated {

struct MediaStreamInfo
{
    using CppType = ::QMedia::Api::MediaStreamInfo;
    using ObjcType = QMediaStreamInfo*;

    using Boxed = MediaStreamInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
