// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_segment.djinni

#import "QMediaStreamInfo.h"


int32_t const QMediaStreamInfoMediaUnknow = 0;

int32_t const QMediaStreamInfoMediaVideo = 1;

int32_t const QMediaStreamInfoMediaAudio = 2;

@implementation QMediaStreamInfo

- (nonnull instancetype)initWithMediaType:(int32_t)mediaType
                                 duration:(int64_t)duration
                                     gops:(nonnull NSArray<NSNumber *> *)gops
                                audioDesc:(nullable QAudioDescription *)audioDesc
                                videoDesc:(nullable QVideoDescription *)videoDesc
{
    if (self = [super init]) {
        _mediaType = mediaType;
        _duration = duration;
        _gops = [gops copy];
        _audioDesc = audioDesc;
        _videoDesc = videoDesc;
    }
    return self;
}

+ (nonnull instancetype)mediaStreamInfoWithMediaType:(int32_t)mediaType
                                            duration:(int64_t)duration
                                                gops:(nonnull NSArray<NSNumber *> *)gops
                                           audioDesc:(nullable QAudioDescription *)audioDesc
                                           videoDesc:(nullable QVideoDescription *)videoDesc
{
    return [(QMediaStreamInfo*)[self alloc] initWithMediaType:mediaType
                                                     duration:duration
                                                         gops:gops
                                                    audioDesc:audioDesc
                                                    videoDesc:videoDesc];
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p mediaType:%@ duration:%@ gops:%@ audioDesc:%@ videoDesc:%@>", self.class, (void *)self, @(self.mediaType), @(self.duration), self.gops, self.audioDesc, self.videoDesc];
}

@end
