// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_segment.djinni

#import "QMediaStreamInfo+Private.h"
#import "DJIMarshal+Private.h"
#import "QAudioDescription+Private.h"
#import "QVideoDescription+Private.h"
#include <cassert>

namespace djinni_generated {

auto MediaStreamInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.mediaType),
            ::djinni::I64::toCpp(obj.duration),
            ::djinni::List<::djinni::I64>::toCpp(obj.gops),
            ::djinni::Optional<std::experimental::optional, ::djinni_generated::AudioDescription>::toCpp(obj.audioDesc),
            ::djinni::Optional<std::experimental::optional, ::djinni_generated::VideoDescription>::toCpp(obj.videoDesc)};
}

auto MediaStreamInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[QMediaStreamInfo alloc] initWithMediaType:(::djinni::I32::fromCpp(cpp.media_type))
                                              duration:(::djinni::I64::fromCpp(cpp.duration))
                                                  gops:(::djinni::List<::djinni::I64>::fromCpp(cpp.gops))
                                             audioDesc:(::djinni::Optional<std::experimental::optional, ::djinni_generated::AudioDescription>::fromCpp(cpp.audio_desc))
                                             videoDesc:(::djinni::Optional<std::experimental::optional, ::djinni_generated::VideoDescription>::fromCpp(cpp.video_desc))];
}

}  // namespace djinni_generated
