// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QMediaStreamInfo.h"


int32_t const QMediaStreamInfoMediaUnknow = 0;

int32_t const QMediaStreamInfoMediaVideo = 1;

int32_t const QMediaStreamInfoMediaAudio = 2;

int32_t const QMediaStreamInfoCodecUnknow = 0;

int32_t const QMediaStreamInfoCodecH264 = 1;

int32_t const QMediaStreamInfoCodecH265 = 2;

int32_t const QMediaStreamInfoCodecMpeg4 = 3;

int32_t const QMediaStreamInfoCodecVp8 = 4;

int32_t const QMediaStreamInfoCodecVp9 = 5;

int32_t const QMediaStreamInfoCodecMp3 = 11;

int32_t const QMediaStreamInfoCodecAac = 12;

int32_t const QMediaStreamInfoCodecOpus = 11;

int32_t const QMediaStreamInfoCodecPcma = 13;

int32_t const QMediaStreamInfoCodecPcmu = 14;

@implementation QMediaStreamInfo

- (nonnull instancetype)initWithMediaType:(int32_t)mediaType
                                codecType:(int32_t)codecType
                                 duration:(int64_t)duration
                                  bitrate:(int64_t)bitrate
                                 streamId:(int32_t)streamId
                                     gops:(nonnull NSArray<NSNumber *> *)gops
                              timebaseNum:(int32_t)timebaseNum
                              timebaseDen:(int32_t)timebaseDen
                                    aDesc:(nonnull QAudioDescription *)aDesc
                                    vDesc:(nonnull QVideoDescription *)vDesc
{
    if (self = [super init]) {
        _mediaType = mediaType;
        _codecType = codecType;
        _duration = duration;
        _bitrate = bitrate;
        _streamId = streamId;
        _gops = [gops copy];
        _timebaseNum = timebaseNum;
        _timebaseDen = timebaseDen;
        _aDesc = aDesc;
        _vDesc = vDesc;
    }
    return self;
}

+ (nonnull instancetype)mediaStreamInfoWithMediaType:(int32_t)mediaType
                                           codecType:(int32_t)codecType
                                            duration:(int64_t)duration
                                             bitrate:(int64_t)bitrate
                                            streamId:(int32_t)streamId
                                                gops:(nonnull NSArray<NSNumber *> *)gops
                                         timebaseNum:(int32_t)timebaseNum
                                         timebaseDen:(int32_t)timebaseDen
                                               aDesc:(nonnull QAudioDescription *)aDesc
                                               vDesc:(nonnull QVideoDescription *)vDesc
{
    return [(QMediaStreamInfo*)[self alloc] initWithMediaType:mediaType
                                                    codecType:codecType
                                                     duration:duration
                                                      bitrate:bitrate
                                                     streamId:streamId
                                                         gops:gops
                                                  timebaseNum:timebaseNum
                                                  timebaseDen:timebaseDen
                                                        aDesc:aDesc
                                                        vDesc:vDesc];
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p mediaType:%@ codecType:%@ duration:%@ bitrate:%@ streamId:%@ gops:%@ timebaseNum:%@ timebaseDen:%@ aDesc:%@ vDesc:%@>", self.class, (void *)self, @(self.mediaType), @(self.codecType), @(self.duration), @(self.bitrate), @(self.streamId), self.gops, @(self.timebaseNum), @(self.timebaseDen), self.aDesc, self.vDesc];
}

@end
