// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QRect4f+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Rect4f::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::F32::toCpp(obj.left),
            ::djinni::F32::toCpp(obj.top),
            ::djinni::F32::toCpp(obj.right),
            ::djinni::F32::toCpp(obj.bottom)};
}

auto Rect4f::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[QRect4f alloc] initWithLeft:(::djinni::F32::fromCpp(cpp.left))
                                     top:(::djinni::F32::fromCpp(cpp.top))
                                   right:(::djinni::F32::fromCpp(cpp.right))
                                  bottom:(::djinni::F32::fromCpp(cpp.bottom))];
}

}  // namespace djinni_generated
