// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QRect4f.h"
#include "rect4f.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QRect4f;

namespace djinni_generated {

struct Rect4f
{
    using CppType = ::QMedia::Api::Rect4f;
    using ObjcType = QRect4f*;

    using Boxed = Rect4f;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
