// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QSize.h"


@implementation QSize

- (nonnull instancetype)initWithWidth:(int64_t)width
                               height:(int64_t)height
{
    if (self = [super init]) {
        _width = width;
        _height = height;
    }
    return self;
}

+ (nonnull instancetype)sizeWithWidth:(int64_t)width
                               height:(int64_t)height
{
    return [(QSize*)[self alloc] initWithWidth:width
                                        height:height];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[QSize class]]) {
        return NO;
    }
    QSize *typedOther = (QSize *)other;
    return self.width == typedOther.width &&
            self.height == typedOther.height;
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            (NSUInteger)self.width ^
            (NSUInteger)self.height;
}

// consturct with json
- (nonnull instancetype)initWithJson:(nonnull NSDictionary*)json {
    if (self = [super init]) {
        NSNumber* width = [json valueForKey:@"width"];
        if (width != nil) {
            _width = [width longValue];
        }
        NSNumber* height = [json valueForKey:@"height"];
        if (height != nil) {
            _height = [height longValue];
        }
    }
    return self;
}
// serialize to json
- (nonnull NSDictionary*) toJson {
    NSDictionary* root = [NSMutableDictionary new];
    [root setValue:@(self.width) forKey:@"width"];
    [root setValue:@(self.height) forKey:@"height"];
    return root;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p width:%@ height:%@>", self.class, (void *)self, @(self.width), @(self.height)];
}

@end
