// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QSize.h"
#include "size.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QSize;

namespace djinni_generated {

struct Size
{
    using CppType = ::QMedia::Api::Size;
    using ObjcType = QSize*;

    using Boxed = Size;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
