// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import <Foundation/Foundation.h>
#import <Foundation/NSDictionary.h>

@interface QSize : NSObject
- (nonnull instancetype)initWithWidth:(int64_t)width
                               height:(int64_t)height;
+ (nonnull instancetype)sizeWithWidth:(int64_t)width
                               height:(int64_t)height;
- (nonnull instancetype)initWithJson:(nonnull NSDictionary*)json;
- (nonnull NSDictionary*)toJson;

@property (nonatomic, readonly) int64_t width;

@property (nonatomic, readonly) int64_t height;

@end
