// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QTimeRange.h"


@implementation QTimeRange

- (nonnull instancetype)initWithStart:(int64_t)start
                                  end:(int64_t)end
{
    if (self = [super init]) {
        _start = start;
        _end = end;
    }
    return self;
}

+ (nonnull instancetype)timeRangeWithStart:(int64_t)start
                                       end:(int64_t)end
{
    return [(QTimeRange*)[self alloc] initWithStart:start
                                                end:end];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[QTimeRange class]]) {
        return NO;
    }
    QTimeRange *typedOther = (QTimeRange *)other;
    return self.start == typedOther.start &&
            self.end == typedOther.end;
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            (NSUInteger)self.start ^
            (NSUInteger)self.end;
}

// consturct with json
- (nonnull instancetype)initWithJson:(nonnull NSDictionary*)json {
    if (self = [super init]) {
        NSNumber* start = [json valueForKey:@"start"];
        if (start != nil) {
            _start = [start longValue];
        }
        NSNumber* end = [json valueForKey:@"end"];
        if (end != nil) {
            _end = [end longValue];
        }
    }
    return self;
}
// serialize to json
- (nonnull NSDictionary*) toJson {
    NSDictionary* root = [NSMutableDictionary new];
    [root setValue:@(self.start) forKey:@"start"];
    [root setValue:@(self.end) forKey:@"end"];
    return root;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p start:%@ end:%@>", self.class, (void *)self, @(self.start), @(self.end)];
}

@end
