// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import <Foundation/Foundation.h>
#import <Foundation/NSDictionary.h>

@interface QTimeRange : NSObject
- (nonnull instancetype)initWithStart:(int64_t)start
                                  end:(int64_t)end;
+ (nonnull instancetype)timeRangeWithStart:(int64_t)start
                                       end:(int64_t)end;
- (nonnull instancetype)initWithJson:(nonnull NSDictionary*)json;
- (nonnull NSDictionary*)toJson;

@property (nonatomic, readonly) int64_t start;

@property (nonatomic, readonly) int64_t end;

@end
