// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QVec4f.h"
#include "vec4f.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QVec4f;

namespace djinni_generated {

struct Vec4f
{
    using CppType = ::QMedia::Api::Vec4f;
    using ObjcType = QVec4f*;

    using Boxed = Vec4f;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
