// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QVec4+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Vec4::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::F32::toCpp(obj.v1),
            ::djinni::F32::toCpp(obj.v2),
            ::djinni::F32::toCpp(obj.v3),
            ::djinni::F32::toCpp(obj.v4)};
}

auto Vec4::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[QVec4 alloc] initWithV1:(::djinni::F32::fromCpp(cpp.v1))
                                  v2:(::djinni::F32::fromCpp(cpp.v2))
                                  v3:(::djinni::F32::fromCpp(cpp.v3))
                                  v4:(::djinni::F32::fromCpp(cpp.v4))];
}

}  // namespace djinni_generated
