// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import <Foundation/Foundation.h>
#import <Foundation/NSDictionary.h>

@interface QVec4 : NSObject
- (nonnull instancetype)initWithV1:(float)v1
                                v2:(float)v2
                                v3:(float)v3
                                v4:(float)v4;
+ (nonnull instancetype)vec4WithV1:(float)v1
                                v2:(float)v2
                                v3:(float)v3
                                v4:(float)v4;
- (nonnull instancetype)initWithJson:(nonnull NSDictionary*)json;
- (nonnull NSDictionary*)toJson;

@property (nonatomic, readonly) float v1;

@property (nonatomic, readonly) float v2;

@property (nonatomic, readonly) float v3;

@property (nonatomic, readonly) float v4;

@end
