// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QVec3f+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Vec3f::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::F32::toCpp(obj.v1),
            ::djinni::F32::toCpp(obj.v2),
            ::djinni::F32::toCpp(obj.v3)};
}

auto Vec3f::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[QVec3f alloc] initWithV1:(::djinni::F32::fromCpp(cpp.v1))
                                   v2:(::djinni::F32::fromCpp(cpp.v2))
                                   v3:(::djinni::F32::fromCpp(cpp.v3))];
}

}  // namespace djinni_generated
