// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_node.djinni

#import "QAnimator.h"
#import "QBlendfunc.h"
#import "QColor4f.h"
#import "QPoint.h"
#import "QRect4f.h"
#import "QSize.h"
#import "QVec3f.h"
#import <Foundation/Foundation.h>


@interface QVideoRenderNode : NSObject

- (void)setVisible:(BOOL)visible;

- (BOOL)getVisible;

- (void)setPosition:(nonnull QPoint *)position;

- (nonnull QPoint *)getPosition;

- (void)setPositionZ:(int32_t)positionz;

- (int32_t)getPositionZ;

- (void)setScaleX:(float)scalex;

- (float)getScaleX;

- (void)setScaleY:(float)scaley;

- (float)getScaleY;

- (void)setScaleZ:(float)scalez;

- (float)getScaleZ;

- (void)setContentSize:(nonnull QSize *)contentSize;

- (nonnull QSize *)getContentSize;

- (void)setRotation:(int32_t)rotation;

- (int32_t)getRotation;

- (void)setRotation3d:(nonnull QVec3f *)rotation3d;

- (nonnull QVec3f *)getRotation3d;

- (void)setAnchorPoint:(nonnull QPoint *)anchorPoint;

- (nonnull QPoint *)getAnchorPoint;

- (void)setColor4F:(nonnull QColor4f *)color;

- (nonnull QColor4f *)getColor4F;

- (void)setAlpha:(float)alpha;

- (float)getAlpha;

- (void)setBlendFunc:(nonnull QBlendfunc *)bf;

- (nonnull QBlendfunc *)getBlendFunc;

- (void)setCrop:(nonnull QRect4f *)crop;

- (nonnull QRect4f *)getCrop;

- (nonnull NSArray<QAnimator *> *)getAnimators;

- (BOOL)addAnimator:(nonnull QAnimator *)animator;

- (BOOL)removeAnimator:(nonnull QAnimator *)animator;

@end
