// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QVideoDescription.h"


int16_t const QVideoDescriptionFormatUnknow = -1;

int16_t const QVideoDescriptionFormatI420 = 0;

int16_t const QVideoDescriptionFormatYv12 = 1;

int16_t const QVideoDescriptionFormatNv12 = 2;

int16_t const QVideoDescriptionFormatNv21 = 3;

int16_t const QVideoDescriptionFormatRgba = 4;

int16_t const QVideoDescriptionFormatBgra = 5;

int16_t const QVideoDescriptionFormatSurfaceTexture = 100;

int16_t const QVideoDescriptionFormatCvPixelBuffer = 101;

int16_t const QVideoDescriptionFormatMediaCodecBuffer = 102;

int16_t const QVideoDescriptionFormatOesTexture = 103;

int16_t const QVideoDescriptionFormatGlTexture = 104;

@implementation QVideoDescription

- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                          pixelFormat:(int16_t)pixelFormat
                             rotation:(int32_t)rotation
                            isTexture:(BOOL)isTexture
{
    if (self = [super init]) {
        _width = width;
        _height = height;
        _pixelFormat = pixelFormat;
        _rotation = rotation;
        _isTexture = isTexture;
    }
    return self;
}

+ (nonnull instancetype)videoDescriptionWithWidth:(int32_t)width
                                           height:(int32_t)height
                                      pixelFormat:(int16_t)pixelFormat
                                         rotation:(int32_t)rotation
                                        isTexture:(BOOL)isTexture
{
    return [(QVideoDescription*)[self alloc] initWithWidth:width
                                                    height:height
                                               pixelFormat:pixelFormat
                                                  rotation:rotation
                                                 isTexture:isTexture];
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p width:%@ height:%@ pixelFormat:%@ rotation:%@ isTexture:%@>", self.class, (void *)self, @(self.width), @(self.height), @(self.pixelFormat), @(self.rotation), @(self.isTexture)];
}

@end
