// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import <Foundation/Foundation.h>

@interface QVideoDescription : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                          pixelFormat:(int16_t)pixelFormat
                             rotation:(int32_t)rotation
                            isTexture:(BOOL)isTexture;
+ (nonnull instancetype)videoDescriptionWithWidth:(int32_t)width
                                           height:(int32_t)height
                                      pixelFormat:(int16_t)pixelFormat
                                         rotation:(int32_t)rotation
                                        isTexture:(BOOL)isTexture;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) int16_t pixelFormat;

@property (nonatomic, readonly) int32_t rotation;

@property (nonatomic, readonly) BOOL isTexture;

@end

extern int16_t const QVideoDescriptionFormatUnknow;
extern int16_t const QVideoDescriptionFormatI420;
extern int16_t const QVideoDescriptionFormatYv12;
extern int16_t const QVideoDescriptionFormatNv12;
extern int16_t const QVideoDescriptionFormatNv21;
extern int16_t const QVideoDescriptionFormatRgba;
extern int16_t const QVideoDescriptionFormatBgra;
/**platform formats */
extern int16_t const QVideoDescriptionFormatSurfaceTexture;
extern int16_t const QVideoDescriptionFormatCvPixelBuffer;
extern int16_t const QVideoDescriptionFormatMediaCodecBuffer;
extern int16_t const QVideoDescriptionFormatOesTexture;
extern int16_t const QVideoDescriptionFormatGlTexture;
