// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_config.djinni

#import "QVideoEncodeOption.h"


int32_t const QVideoEncodeOptionKUnknown = 0;

int32_t const QVideoEncodeOptionKVP8 = 1;

int32_t const QVideoEncodeOptionKVP9 = 2;

int32_t const QVideoEncodeOptionKMPEG4 = 3;

int32_t const QVideoEncodeOptionKH264 = 4;

int32_t const QVideoEncodeOptionKH265 = 5;

int32_t const QVideoEncodeOptionKI420 = 6;

int32_t const QVideoEncodeOptionProfileBaseline = 0;

int32_t const QVideoEncodeOptionProfileMain = 1;

int32_t const QVideoEncodeOptionProfileHigh = 2;

@implementation QVideoEncodeOption

- (nonnull instancetype)initWithCodectype:(int32_t)codectype
                                    width:(int32_t)width
                                   height:(int32_t)height
                                  bitrate:(int32_t)bitrate
                                framerate:(int32_t)framerate
                                      gop:(int32_t)gop
                                  profile:(int32_t)profile
                                    level:(int32_t)level
                                      ext:(nullable NSString *)ext
{
    if (self = [super init]) {
        _codectype = codectype;
        _width = width;
        _height = height;
        _bitrate = bitrate;
        _framerate = framerate;
        _gop = gop;
        _profile = profile;
        _level = level;
        _ext = [ext copy];
    }
    return self;
}

+ (nonnull instancetype)videoEncodeOptionWithCodectype:(int32_t)codectype
                                                 width:(int32_t)width
                                                height:(int32_t)height
                                               bitrate:(int32_t)bitrate
                                             framerate:(int32_t)framerate
                                                   gop:(int32_t)gop
                                               profile:(int32_t)profile
                                                 level:(int32_t)level
                                                   ext:(nullable NSString *)ext
{
    return [(QVideoEncodeOption*)[self alloc] initWithCodectype:codectype
                                                          width:width
                                                         height:height
                                                        bitrate:bitrate
                                                      framerate:framerate
                                                            gop:gop
                                                        profile:profile
                                                          level:level
                                                            ext:ext];
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p codectype:%@ width:%@ height:%@ bitrate:%@ framerate:%@ gop:%@ profile:%@ level:%@ ext:%@>", self.class, (void *)self, @(self.codectype), @(self.width), @(self.height), @(self.bitrate), @(self.framerate), @(self.gop), @(self.profile), @(self.level), self.ext];
}

@end
