// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QVideoDescription+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto VideoDescription::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.width),
            ::djinni::I32::toCpp(obj.height),
            ::djinni::I16::toCpp(obj.pixelFormat),
            ::djinni::I32::toCpp(obj.rotation),
            ::djinni::Bool::toCpp(obj.isTexture)};
}

auto VideoDescription::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[QVideoDescription alloc] initWithWidth:(::djinni::I32::fromCpp(cpp.width))
                                             height:(::djinni::I32::fromCpp(cpp.height))
                                        pixelFormat:(::djinni::I16::fromCpp(cpp.pixel_format))
                                           rotation:(::djinni::I32::fromCpp(cpp.rotation))
                                          isTexture:(::djinni::Bool::fromCpp(cpp.is_texture))];
}

}  // namespace djinni_generated
