// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_config.djinni

#import "QVideoEncodeOption+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto VideoEncodeOption::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.codectype),
            ::djinni::I32::toCpp(obj.width),
            ::djinni::I32::toCpp(obj.height),
            ::djinni::I32::toCpp(obj.bitrate),
            ::djinni::I32::toCpp(obj.framerate),
            ::djinni::I32::toCpp(obj.gop),
            ::djinni::I32::toCpp(obj.profile),
            ::djinni::I32::toCpp(obj.level),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.ext)};
}

auto VideoEncodeOption::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[QVideoEncodeOption alloc] initWithCodectype:(::djinni::I32::fromCpp(cpp.codectype))
                                                   width:(::djinni::I32::fromCpp(cpp.width))
                                                  height:(::djinni::I32::fromCpp(cpp.height))
                                                 bitrate:(::djinni::I32::fromCpp(cpp.bitrate))
                                               framerate:(::djinni::I32::fromCpp(cpp.framerate))
                                                     gop:(::djinni::I32::fromCpp(cpp.gop))
                                                 profile:(::djinni::I32::fromCpp(cpp.profile))
                                                   level:(::djinni::I32::fromCpp(cpp.level))
                                                     ext:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.ext))];
}

}  // namespace djinni_generated
