// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import <Foundation/Foundation.h>

@interface QVideoDescription : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                            framerate:(int32_t)framerate
                          pixelFormat:(int16_t)pixelFormat
                             rotation:(int32_t)rotation
                            isTexture:(BOOL)isTexture
                              profile:(int32_t)profile
                                level:(int32_t)level
                           colorRange:(int32_t)colorRange
                           colorSpace:(int32_t)colorSpace
                             colorTrc:(int32_t)colorTrc
                       colorPrimaries:(int32_t)colorPrimaries
                       aspectRatioNum:(int32_t)aspectRatioNum
                       aspectRatioDen:(int32_t)aspectRatioDen;
+ (nonnull instancetype)videoDescriptionWithWidth:(int32_t)width
                                           height:(int32_t)height
                                        framerate:(int32_t)framerate
                                      pixelFormat:(int16_t)pixelFormat
                                         rotation:(int32_t)rotation
                                        isTexture:(BOOL)isTexture
                                          profile:(int32_t)profile
                                            level:(int32_t)level
                                       colorRange:(int32_t)colorRange
                                       colorSpace:(int32_t)colorSpace
                                         colorTrc:(int32_t)colorTrc
                                   colorPrimaries:(int32_t)colorPrimaries
                                   aspectRatioNum:(int32_t)aspectRatioNum
                                   aspectRatioDen:(int32_t)aspectRatioDen;

@property (nonatomic ) int32_t width;

@property (nonatomic ) int32_t height;

@property (nonatomic ) int32_t framerate;

@property (nonatomic ) int16_t pixelFormat;

@property (nonatomic ) int32_t rotation;

@property (nonatomic ) BOOL isTexture;

/** ff field */
@property (nonatomic ) int32_t profile;

@property (nonatomic ) int32_t level;

@property (nonatomic ) int32_t colorRange;

@property (nonatomic ) int32_t colorSpace;

@property (nonatomic ) int32_t colorTrc;

@property (nonatomic ) int32_t colorPrimaries;

/** aspect_ratio */
@property (nonatomic ) int32_t aspectRatioNum;

@property (nonatomic ) int32_t aspectRatioDen;

@end

extern int16_t const QVideoDescriptionFormatUnknow;
extern int16_t const QVideoDescriptionFormatI420;
extern int16_t const QVideoDescriptionFormatYv12;
extern int16_t const QVideoDescriptionFormatNv12;
extern int16_t const QVideoDescriptionFormatNv21;
extern int16_t const QVideoDescriptionFormatRgba;
extern int16_t const QVideoDescriptionFormatBgra;
/**platform formats */
extern int16_t const QVideoDescriptionFormatSurfaceTexture;
extern int16_t const QVideoDescriptionFormatCvPixelBuffer;
extern int16_t const QVideoDescriptionFormatMediaCodecBuffer;
extern int16_t const QVideoDescriptionFormatOesTexture;
extern int16_t const QVideoDescriptionFormatGlTexture;
