// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_config.djinni

#import <Foundation/Foundation.h>

@interface QVideoEncodeOption : NSObject
- (nonnull instancetype)initWithCodectype:(int32_t)codectype
                                    width:(int32_t)width
                                   height:(int32_t)height
                                  bitrate:(int32_t)bitrate
                                framerate:(int32_t)framerate
                                      gop:(int32_t)gop
                                  profile:(int32_t)profile
                                    level:(int32_t)level
                                      ext:(nullable NSString *)ext;
+ (nonnull instancetype)videoEncodeOptionWithCodectype:(int32_t)codectype
                                                 width:(int32_t)width
                                                height:(int32_t)height
                                               bitrate:(int32_t)bitrate
                                             framerate:(int32_t)framerate
                                                   gop:(int32_t)gop
                                               profile:(int32_t)profile
                                                 level:(int32_t)level
                                                   ext:(nullable NSString *)ext;

@property (nonatomic ) int32_t codectype;

@property (nonatomic ) int32_t width;

@property (nonatomic ) int32_t height;

@property (nonatomic ) int32_t bitrate;

@property (nonatomic ) int32_t framerate;

@property (nonatomic ) int32_t gop;

@property (nonatomic ) int32_t profile;

@property (nonatomic ) int32_t level;

@property (nonatomic , nullable) NSString * ext;

@end

/** codectype */
extern int32_t const QVideoEncodeOptionKUnknown;
extern int32_t const QVideoEncodeOptionKVP8;
extern int32_t const QVideoEncodeOptionKVP9;
extern int32_t const QVideoEncodeOptionKMPEG4;
extern int32_t const QVideoEncodeOptionKH264;
extern int32_t const QVideoEncodeOptionKH265;
extern int32_t const QVideoEncodeOptionKI420;
/** profile */
extern int32_t const QVideoEncodeOptionProfileBaseline;
extern int32_t const QVideoEncodeOptionProfileMain;
extern int32_t const QVideoEncodeOptionProfileHigh;
