// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#import "QVideoDescription.h"
#include "video_description.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class QVideoDescription;

namespace djinni_generated {

struct VideoDescription
{
    using CppType = ::QMedia::Api::VideoDescription;
    using ObjcType = QVideoDescription*;

    using Boxed = VideoDescription;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
