// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from video_runloop.djinni

#import <Foundation/Foundation.h>


@interface QVideoRender : NSObject

- (void)setDisplayMode:(int32_t)mode
                 flipV:(BOOL)flipV;

- (void)OnViewSizeChange:(int32_t)width
                  height:(int32_t)height;

- (void)onViewCreate:(int32_t)width
              height:(int32_t)height;

- (BOOL)onDraw:(int64_t)pirv;

- (void)onViewDestroy;

@end
