// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_node.djinni

#pragma once

#include "media_range.h"
#include "vec4f.h"
#include <cstdint>
#include <string>
#include <utility>

namespace QMedia { namespace Api {

struct Animator final {
    static const std::string POSITIONXYZ;

    static const std::string ROTATION;

    static const std::string ROTATIONXYZ;

    std::string name;
    std::string property;
    MediaRange timerang;
    Vec4f startpoint;
    Vec4f endpoint;
    int32_t easefunction;
    bool repleat;

    Animator() {}

    Animator(std::string name_,
             std::string property_,
             MediaRange timerang_,
             Vec4f startpoint_,
             Vec4f endpoint_,
             int32_t easefunction_,
             bool repleat_)
    : name(std::move(name_))
    , property(std::move(property_))
    , timerang(std::move(timerang_))
    , startpoint(std::move(startpoint_))
    , endpoint(std::move(endpoint_))
    , easefunction(std::move(easefunction_))
    , repleat(std::move(repleat_))
    {}
};

} }  // namespace QMedia::Api
