// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_config.djinni

#include "audio_encode_option.h"  // my header

namespace QMedia { namespace Api {

int32_t const AudioEncodeOption::KUNKNOWN = 0;

int32_t const AudioEncodeOption::KAAC = 10;

int32_t const AudioEncodeOption::KOPUS = 11;

int32_t const AudioEncodeOption::KMPEG4 = 12;

int32_t const AudioEncodeOption::KPCMA = 13;

int32_t const AudioEncodeOption::KPCMU = 14;

int32_t const AudioEncodeOption::KG722 = 15;

int32_t const AudioEncodeOption::KAAC_LATM = 16;

int32_t const AudioEncodeOption::KMP3 = 17;

} }  // namespace QMedia::Api
