// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "audio_description.h"  // my header

namespace QMedia { namespace Api {

int16_t const AudioDescription::FORMAT_UNKNOW = -1;

int16_t const AudioDescription::FORMAT_U8 = 0;

int16_t const AudioDescription::FORMAT_S16 = 1;

int16_t const AudioDescription::FORMAT_U16 = 2;

int16_t const AudioDescription::FORMAT_S32 = 3;

int16_t const AudioDescription::FORMAT_U32 = 4;

int16_t const AudioDescription::FORMAT_FLOAT = 5;

int16_t const AudioDescription::FORMAT_SAMPLEBUFFER = 100;

int16_t const AudioDescription::FORMAT_BYTEARRAY = 101;

} }  // namespace QMedia::Api
