// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_node.djinni

#pragma once

namespace QMedia { namespace Api {

class AudioRenderNode {
public:
    virtual ~AudioRenderNode() {}

    virtual void setTempo(float tempo) = 0;

    virtual void setRate(float rate) = 0;

    virtual void setPitch(float pitch) = 0;

    virtual void setVolume(float volume) = 0;
};

} }  // namespace QMedia::Api
