// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace QMedia { namespace Api {

struct Blendfunc final {
    static const int32_t ZERO;

    static const int32_t ONE;

    static const int32_t SRC_COLOR;

    static const int32_t ONE_MINUS_SRC_COLOR;

    static const int32_t SRC_ALPHA;

    static const int32_t ONE_MINUS_SRC_ALPHA;

    static const int32_t DST_ALPHA;

    static const int32_t ONE_MINUS_DST_ALPHA;

    static const int32_t DST_COLOR;

    static const int32_t ONE_MINUS_DST_COLOR;

    static const int32_t SRC_ALPHA_SATURATE;

    int32_t src;
    int32_t dst;

    friend bool operator==(const Blendfunc& lhs, const Blendfunc& rhs);
    friend bool operator!=(const Blendfunc& lhs, const Blendfunc& rhs);

    Blendfunc() {}

    Blendfunc(int32_t src_,
              int32_t dst_)
    : src(std::move(src_))
    , dst(std::move(dst_))
    {}
};

} }  // namespace QMedia::Api
