// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "blendfunc.h"  // my header

namespace QMedia { namespace Api {

int32_t const Blendfunc::ZERO = 0;

int32_t const Blendfunc::ONE = 1;

int32_t const Blendfunc::SRC_COLOR = 768;

int32_t const Blendfunc::ONE_MINUS_SRC_COLOR = 769;

int32_t const Blendfunc::SRC_ALPHA = 770;

int32_t const Blendfunc::ONE_MINUS_SRC_ALPHA = 771;

int32_t const Blendfunc::DST_ALPHA = 772;

int32_t const Blendfunc::ONE_MINUS_DST_ALPHA = 773;

int32_t const Blendfunc::DST_COLOR = 774;

int32_t const Blendfunc::ONE_MINUS_DST_COLOR = 775;

int32_t const Blendfunc::SRC_ALPHA_SATURATE = 776;

bool operator==(const Blendfunc& lhs, const Blendfunc& rhs) {
    return lhs.src == rhs.src &&
           lhs.dst == rhs.dst;
}

bool operator!=(const Blendfunc& lhs, const Blendfunc& rhs) {
    return !(lhs == rhs);
}

} }  // namespace QMedia::Api
