// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "color4f.h"  // my header

namespace QMedia { namespace Api {


bool operator==(const Color4f& lhs, const Color4f& rhs) {
    return lhs.r == rhs.r &&
           lhs.g == rhs.g &&
           lhs.b == rhs.b &&
           lhs.a == rhs.a;
}

bool operator!=(const Color4f& lhs, const Color4f& rhs) {
    return !(lhs == rhs);
}

} }  // namespace QMedia::Api
