// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include <utility>

namespace QMedia { namespace Api {

struct Color4f final {
    float r;
    float g;
    float b;
    float a;

    friend bool operator==(const Color4f& lhs, const Color4f& rhs);
    friend bool operator!=(const Color4f& lhs, const Color4f& rhs);

    Color4f() {}

    Color4f(float r_,
            float g_,
            float b_,
            float a_)
    : r(std::move(r_))
    , g(std::move(g_))
    , b(std::move(b_))
    , a(std::move(a_))
    {}
};

} }  // namespace QMedia::Api
