// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace QMedia { namespace Api {

class EditorExporterCallback;
class MediaSessionInternal;
struct AudioEncodeOption;
struct VideoEncodeOption;

class EditorExporterInternal {
public:
    virtual ~EditorExporterInternal() {}
    /** error code */
    static const int32_t E_STATE;

    static const int32_t E_SYSTEM;

    static const int32_t UNKNOW;

    static const int32_t OK;


    virtual std::shared_ptr<MediaSessionInternal> getSession() = 0;

    virtual void setCallback(const std::shared_ptr<EditorExporterCallback> & callback) = 0;

    virtual void setAudioOption(const AudioEncodeOption & option) = 0;

    virtual void setVideoOption(const VideoEncodeOption & option) = 0;

    virtual int64_t getPosition() = 0;

    virtual void start() = 0;

    virtual void cancel() = 0;
};

} }  // namespace QMedia::Api
