// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#include "editor_exporter_internal.h"  // my header

namespace QMedia { namespace Api {

int32_t const EditorExporterInternal::E_STATE = -3;

int32_t const EditorExporterInternal::E_SYSTEM = -2;

int32_t const EditorExporterInternal::UNKNOW = -1;

int32_t const EditorExporterInternal::OK = 0;

} }  // namespace QMedia::Api
