// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace QMedia { namespace Api {

class EditorExporterCallback;
class MediaSessionInternal;

class EditorExporterInternal {
public:
    virtual ~EditorExporterInternal() {}
    /** error code */
    static const int32_t E_STATE = -3;

    static const int32_t E_SYSTEM = -2;

    static const int32_t UNKNOW = -1;

    static const int32_t OK = 0;


    virtual std::shared_ptr<MediaSessionInternal> getSession() = 0;

    virtual void setCallback(const std::shared_ptr<EditorExporterCallback> & callback) = 0;

    virtual void cancel() = 0;
};

} }  // namespace QMedia::Api
