// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#pragma once

#include <cstdint>

namespace QMedia { namespace Api {

class EditorPlayerCallback {
public:
    virtual ~EditorPlayerCallback() {}

    virtual void onStarted(int32_t code) = 0;

    virtual void onStoped(int32_t code) = 0;

    virtual void onSeekTo(int64_t time_ms) = 0;

    virtual void onProgressUpdated(int64_t time_ms) = 0;

    virtual void onPlayerStateChanged(int32_t new_state, int32_t old_state) = 0;

    virtual void onCompleted() = 0;
};

} }  // namespace QMedia::Api
