// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#pragma once

#include <cstdint>

namespace QMedia { namespace Api {

class EditorExporterCallback {
public:
    virtual ~EditorExporterCallback() {}

    virtual void onStarted(int32_t code) = 0;

    virtual void onStoped(int32_t code) = 0;

    virtual void onProgressUpdated(int64_t time_ms) = 0;

    virtual void onCanceled(int32_t code) = 0;

    virtual void onCompleted() = 0;
};

} }  // namespace QMedia::Api
