// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_session.djinni

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>

namespace QMedia { namespace Api {

class EditorPlayerCallback {
public:
    virtual ~EditorPlayerCallback() {}

    virtual void onPrepare(int32_t code) = 0;

    virtual void onStarted(int32_t code) = 0;

    virtual void onStoped(int32_t code) = 0;

    virtual void onSeekTo(int64_t time_ms) = 0;

    virtual void onProgressUpdated(int64_t time_ms) = 0;

    virtual void onCompleted(int32_t code) = 0;

    virtual void onEvent(int32_t eventid, const std::unordered_map<std::string, std::string> & msg) = 0;
};

} }  // namespace QMedia::Api
