// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "media_stream_info.h"  // my header

namespace QMedia { namespace Api {

int32_t const MediaStreamInfo::MEDIA_UNKNOW = 0;

int32_t const MediaStreamInfo::MEDIA_VIDEO = 1;

int32_t const MediaStreamInfo::MEDIA_AUDIO = 2;

int32_t const MediaStreamInfo::CODEC_UNKNOW = 0;

int32_t const MediaStreamInfo::CODEC_H264 = 1;

int32_t const MediaStreamInfo::CODEC_H265 = 2;

int32_t const MediaStreamInfo::CODEC_MPEG4 = 3;

int32_t const MediaStreamInfo::CODEC_VP8 = 4;

int32_t const MediaStreamInfo::CODEC_VP9 = 5;

int32_t const MediaStreamInfo::CODEC_MP3 = 11;

int32_t const MediaStreamInfo::CODEC_AAC = 12;

int32_t const MediaStreamInfo::CODEC_OPUS = 11;

int32_t const MediaStreamInfo::CODEC_PCMA = 13;

int32_t const MediaStreamInfo::CODEC_PCMU = 14;

} }  // namespace QMedia::Api
