// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include "audio_description.h"
#include "video_description.h"
#include <cstdint>
#include <utility>
#include <vector>

namespace QMedia { namespace Api {

struct MediaStreamInfo final {
    /** media type */
    static const int32_t MEDIA_UNKNOW;

    static const int32_t MEDIA_VIDEO;

    static const int32_t MEDIA_AUDIO;

    /** codec type */
    static const int32_t CODEC_UNKNOW;

    static const int32_t CODEC_H264;

    static const int32_t CODEC_H265;

    static const int32_t CODEC_MPEG4;

    static const int32_t CODEC_VP8;

    static const int32_t CODEC_VP9;

    static const int32_t CODEC_MP3;

    static const int32_t CODEC_AAC;

    static const int32_t CODEC_OPUS;

    static const int32_t CODEC_PCMA;

    static const int32_t CODEC_PCMU;

    int32_t media_type;
    int32_t codec_type;
    int64_t duration;
    int64_t bitrate;
    int32_t stream_id;
    std::vector<int64_t> gops;
    /** timebase */
    int32_t timebase_num;
    int32_t timebase_den;
    AudioDescription a_desc;
    VideoDescription v_desc;

    MediaStreamInfo() {}

    MediaStreamInfo(int32_t media_type_,
                    int32_t codec_type_,
                    int64_t duration_,
                    int64_t bitrate_,
                    int32_t stream_id_,
                    std::vector<int64_t> gops_,
                    int32_t timebase_num_,
                    int32_t timebase_den_,
                    AudioDescription a_desc_,
                    VideoDescription v_desc_)
    : media_type(std::move(media_type_))
    , codec_type(std::move(codec_type_))
    , duration(std::move(duration_))
    , bitrate(std::move(bitrate_))
    , stream_id(std::move(stream_id_))
    , gops(std::move(gops_))
    , timebase_num(std::move(timebase_num_))
    , timebase_den(std::move(timebase_den_))
    , a_desc(std::move(a_desc_))
    , v_desc(std::move(v_desc_))
    {}
};

} }  // namespace QMedia::Api
