// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "point.h"  // my header

namespace QMedia { namespace Api {


bool operator==(const Point& lhs, const Point& rhs) {
    return lhs.x == rhs.x &&
           lhs.y == rhs.y;
}

bool operator!=(const Point& lhs, const Point& rhs) {
    return !(lhs == rhs);
}

} }  // namespace QMedia::Api
