// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "rect4f.h"  // my header

namespace QMedia { namespace Api {


bool operator==(const Rect4f& lhs, const Rect4f& rhs) {
    return lhs.left == rhs.left &&
           lhs.top == rhs.top &&
           lhs.right == rhs.right &&
           lhs.bottom == rhs.bottom;
}

bool operator!=(const Rect4f& lhs, const Rect4f& rhs) {
    return !(lhs == rhs);
}

} }  // namespace QMedia::Api
