// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace QMedia { namespace Api {

struct TimeRange final {
    int64_t start;
    int64_t end;

    bool operator==(const TimeRange& rhs) {
        return start == rhs.start &&
               end == rhs.end;
    }

    bool operator!=(const TimeRange& rhs) {
        return !((*this) == rhs);
    }

    TimeRange() {}

    TimeRange(int64_t start_,
              int64_t end_)
    : start(std::move(start_))
    , end(std::move(end_))
    {}
};

} }  // namespace QMedia::Api
