// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "vec3f.h"  // my header

namespace QMedia { namespace Api {


bool operator==(const Vec3f& lhs, const Vec3f& rhs) {
    return lhs.v1 == rhs.v1 &&
           lhs.v2 == rhs.v2 &&
           lhs.v3 == rhs.v3;
}

bool operator!=(const Vec3f& lhs, const Vec3f& rhs) {
    return !(lhs == rhs);
}

} }  // namespace QMedia::Api
