// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "vec4f.h"  // my header

namespace QMedia { namespace Api {


bool operator==(const Vec4f& lhs, const Vec4f& rhs) {
    return lhs.v1 == rhs.v1 &&
           lhs.v2 == rhs.v2 &&
           lhs.v3 == rhs.v3 &&
           lhs.v4 == rhs.v4;
}

bool operator!=(const Vec4f& lhs, const Vec4f& rhs) {
    return !(lhs == rhs);
}

} }  // namespace QMedia::Api
