// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_node.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace QMedia { namespace Api {

struct Animator;
struct Point;
struct Size;
struct Vec4f;

class VideoRenderNode {
public:
    virtual ~VideoRenderNode() {}

    virtual void setVisible(bool visible) = 0;

    virtual void setAlpha(float alpha) = 0;

    virtual void setCrop(const Vec4f & crop) = 0;

    virtual void setContentSize(const Size & content_size) = 0;

    virtual void setAnchorPoint(const Point & anchor_point) = 0;

    virtual void setPosition(const Point & position) = 0;

    virtual void setPositionZ(int32_t positionz) = 0;

    virtual void setRotation(int32_t rotation) = 0;

    virtual void setRotation3d(const Vec4f & rotation3d) = 0;

    virtual void setScaleX(float scalex) = 0;

    virtual void setScaleY(float scaley) = 0;

    virtual void setScaleZ(float scalez) = 0;

    virtual std::vector<Animator> getAnimators() = 0;

    virtual bool addAnimator(const Animator & animator) = 0;

    virtual bool removeAnimator(const Animator & animator) = 0;
};

} }  // namespace QMedia::Api
