// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from video_runloop.djinni

#pragma once

#include <cstdint>

namespace QMedia { namespace Api {

class VideoRender {
public:
    virtual ~VideoRender() {}

    virtual void setDisplayMode(int32_t mode, bool flip_v) = 0;

    virtual void onViewSizeChange(int32_t width, int32_t height) = 0;

    virtual void onViewDestroy() = 0;

    virtual bool onDraw(int64_t time_ms, bool no_display) = 0;

    virtual bool readRGBA(void* buffer, int32_t width, int32_t height, int32_t format) = 0;
};

} }  // namespace QMedia::Api
