// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace QMedia { namespace Api {

struct VideoDescription final {
    static const int16_t FORMAT_UNKNOW = -1;

    static const int16_t FORMAT_I420 = 0;

    static const int16_t FORMAT_YV12 = 1;

    static const int16_t FORMAT_NV12 = 2;

    static const int16_t FORMAT_NV21 = 3;

    static const int16_t FORMAT_RGBA = 4;

    static const int16_t FORMAT_BGRA = 5;

    /**platform formats */
    static const int16_t FORMAT_SURFACETEXTURE = 100;

    static const int16_t FORMAT_CVPIXELBUFFER = 101;

    static const int16_t FORMAT_MEDIACODECBUFFER = 102;

    static const int16_t FORMAT_OESTEXTURE = 103;

    static const int16_t FORMAT_GLTEXTURE = 104;

    int32_t width;
    int32_t height;
    int16_t pixel_format;
    int32_t rotation;
    bool is_texture;

    VideoDescription() {}

    VideoDescription(int32_t width_,
                     int32_t height_,
                     int16_t pixel_format_,
                     int32_t rotation_,
                     bool is_texture_)
    : width(std::move(width_))
    , height(std::move(height_))
    , pixel_format(std::move(pixel_format_))
    , rotation(std::move(rotation_))
    , is_texture(std::move(is_texture_))
    {}
};

} }  // namespace QMedia::Api
