// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from media_comm.djinni

#include "video_description.h"  // my header

namespace QMedia { namespace Api {

int16_t const VideoDescription::FORMAT_UNKNOW = -1;

int16_t const VideoDescription::FORMAT_I420 = 0;

int16_t const VideoDescription::FORMAT_YV12 = 1;

int16_t const VideoDescription::FORMAT_NV12 = 2;

int16_t const VideoDescription::FORMAT_NV21 = 3;

int16_t const VideoDescription::FORMAT_RGBA = 4;

int16_t const VideoDescription::FORMAT_BGRA = 5;

int16_t const VideoDescription::FORMAT_SURFACETEXTURE = 100;

int16_t const VideoDescription::FORMAT_CVPIXELBUFFER = 101;

int16_t const VideoDescription::FORMAT_MEDIACODECBUFFER = 102;

int16_t const VideoDescription::FORMAT_OESTEXTURE = 103;

int16_t const VideoDescription::FORMAT_GLTEXTURE = 104;

} }  // namespace QMedia::Api
