// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from video_runloop.djinni

#pragma once

#include <memory>

namespace QMedia { namespace Api {

class VideoRender;

class VideoRunloop {
public:
    virtual ~VideoRunloop() {}

    virtual void setVideoRender(const std::shared_ptr<VideoRender> & render) = 0;

    virtual bool start() = 0;

    virtual void stop() = 0;

    virtual void pause(bool isPause) = 0;

    virtual void forceUpdate() = 0;
};

} }  // namespace QMedia::Api
